### ISSUE TITLE
What permissions are required for the github access token?

### ISSUE THREAD

**Issue by RayBB** [release-drafter/release-drafter#1005]
Sorry if this is documented somewhere but my searching didn't come up with a clear answer. 

When creating a new github personal access token (PAT) what permissions / scopes are required? 

I'm guessing it's just full control of repos but it's not clear. Would also be good to add this to the main readme :)

![image](https://user-images.githubusercontent.com/921217/149187859-204e296d-76ae-4eaf-8580-c3ccb5311a9f.png)

**Comment by jetersen** [comment]
The question is why do you need a PAT?

This requires a GitHub app token or it can use the default GitHub action token in GitHub actions.

**Comment by RayBB** [comment]
I didn't realize that `GITHUB_TOKEN` was provided by default so we didn't need to add that to our repo secrets.

Thanks for clarifying
