### ISSUE TITLE
Only consider commits that come before `commitish`?

### ISSUE THREAD

**Issue by mikeroll** [release-drafter/release-drafter#1053]
As I understand right now, only branch names are properly supported as values for `commitish`, having something like a commit sha there does not yield expected results. This is basically a suggestion to support at least commit hashes there (and by extension perhaps everything else?).

Imagine a `master` branch with commits `A -> B -> C (HEAD)` (all of them PR merge commits to keep it simple), and a workflow for that branch which is roughly "test -> build -> run release-drafter". Each of the commits triggers this workflow, and runs for successive commits are not concurrent.
So if the workflow for `B` is running, and `C` is merged meanwhile, I would still like release-drafter to:
- create/update the release targeting commit `B`, since that's what's tested and built so far. Using `commitish: ${{ github.sha }}` works great for creating and https://github.com/release-drafter/release-drafter/pull/1052 enables the same for updating.
- include only `A` and `B` in the release notes. Instead, `C` is also included even though it's not yet "ready", and as I understand there's currently no way to tell it otherwise.

Does this make any sense? :)

Having poked around the code a little I am tempted to try something like `after = commitish` in this query:
https://github.com/release-drafter/release-drafter/blob/master/lib/commits.js#L20
But I wonder if I'm thinking in the right direction.

**Comment by jetersen** [comment]
@mikeroll you should be able to make the changes and have your github action point to your repo/branch and test it out, I would be happy to see releases from this action.
