### ISSUE TITLE
Release drafter should ignore prerelease releases when drafting changelog

### ISSUE THREAD

**Issue by blast-hardcheese** [release-drafter/release-drafter#1135]
Somewhat related to #614

I ran into an issue where someone had manually released a draft as `prerelease`, but the subsequently generated draft did not include the commits from the last stable release.

Presumably this is not intentional, but before I start working on this I'd like to make sure.

Thanks!

**Comment by jetersen** [comment]
Do not assume 😅

I don't think anyone had considered the use case.

So the release drafter should ignore pre-releases when drafting a non pre-release. However when drafting a pre-release then the release drafter should include pre-releases ?

Right hopefully we are thinking the same thing ☺️

**Comment by blast-hardcheese** [comment]
> So the release drafter should ignore pre-releases when drafting a non pre-release. However when drafting a pre-release then the release drafter should include pre-releases ?

For the first case, non pre-release drafts should always be since the last non pre-release.

I could go either way on the pre-release (either total accumulating or incremental changesets).

**Comment by jetersen** [comment]
> I could go either way on the pre-release (either total accumulating or incremental changesets).

True, I am leaning more to total cause that is how the non pre-release would potentially look like.

**Comment by blast-hardcheese** [comment]
I could see the other way as well, so it may be desirable for someone to add a configuration parameter if they need something like this, but I think for now it'll be good enough for all releases, prerelease or not, to do the full draft of all notes from the last non pre-release.

I can't jump on this immediately, but thanks for confirming the direction 🙂

**Comment by hcoohb** [comment]
That would be the last feature to allow me to name release-drafter an absolute must and life-saver!!

At the moment I copy and merge all of the pre-release changelog for the next non-pre-release, but it is a bit time consuming.
This would be a terrific improvement!

**Comment by ssbarnea** [comment]
While release drafter is a wonderful tool, that bug alone is an epic PITA that makes me avoid making pre-releases, just because once I do, I need to do a lot of manual work to rebuild the changelog for the release.

Apparently https://github.com/paperless-ngx/release-drafter fork works, so I am wondering if I should switch to the fork, or there is still hope to get the changes backported here?

**Comment by jetersen** [comment]
PR are always welcome 🤗

**Comment by qcasey** [comment]
Our fork at https://github.com/paperless-ngx/release-drafter bluntly ignores prereleases without any configuration to toggle this behavior. I'm not sure how many people's workflows rely on **not** ignoring prereleases so haven't considered bringing it here upstream.

For anyone curious this is the [super simple change](https://github.com/release-drafter/release-drafter/commit/9c77184a1ca8bf70496a467f23de03138117a160).

**Comment by ssbarnea** [comment]
TBH, by definition a pre-release is an incomplete release, so it should not count as being "last release". I would make the drafting only count releases and keep it like this by default, not even a need to configure that. Still, is not up to me to decide this.

@jetersen Would you accept backporting this change as listed by @qcasey?

**Comment by blast-hardcheese** [comment]
> TBH, by definition a pre-release is an incomplete release, so it should not count as being "last release". I would make the drafting only count releases and keep it like this by default, not even a need to configure that. Still, is not up to me to decide this.
> 
> @jetersen Would you accept backporting this change as listed by @qcasey?

Obviously I'm not @jetersen, but having some experience with this project (and that this issue has not been rejected), I believe this patch would be accepted with some degree of enthusiasm (at least from me!). The only alteration I would request is to make this setting configurable, but other than that I believe this is a very reasonable way to proceed. Thanks in advance!

**Comment by mrfelton** [comment]
+1 to making this configurable. There are scenarios where prereleases should be considered and different scenarios where it should not.
