### ISSUE TITLE
[Question] are multiple drafts possible

### ISSUE THREAD

**Issue by mimmi20** [release-drafter/release-drafter#1205]
I'm using release-drafter to generate Draft Releases in my projects.

In one of these projects, I keep an older branch up to date. For this old branch I also want to use release-drafter, but the generated Draft includes changes from both branches.

Thus my question: Is it possible to generate separate Draft Releases for different Branches?

**Comment by jetersen** [comment]
Yes, see usecase here:

https://github.com/guardrail-dev/guardrail/blob/master/.github/workflows/release-drafter.yml

You don't have to use a script to manage shared config, simply use `_extends` syntax, see docs here: https://github.com/probot/octokit-plugin-config#extends

**Comment by jetersen** [comment]
if you want the older branch to only update draft for it, simply fix the `target-commitish` in config to that branch

**Comment by jetersen** [comment]
Seems `target-commitish` is undocumented, I will fix that for v6!

But `target-commitish` is in the schema and allows you to pull history against it.

**Comment by mimmi20** [comment]
A property named `commitish` is documented. But I dont understand, if I have to write `refs/heads/master` or just `master`.

**Comment by jetersen** [comment]
You do not need to write `commitish` for default branch as that is the default behavior, only your older branch.

`refs/heads/master` and `master` are both correct. I believe in the code we trim `refs/heads/` so just put the branch name

**Comment by mimmi20** [comment]
Thanks
