### ISSUE TITLE
Multiple Tagging support for `tag-template`

### ISSUE THREAD

**Issue by efectn** [release-drafter/release-drafter#1214]
For some projects we need to tag multiple versions per release. For example, if our repository contains sub-modules; we should define multiple tags for package manager. This behavior should fix this problem i suppose:
```yaml
name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: ['v$RESOLVED_VERSION', 'service/submodule/v$RESOLVED_VERSION']
```

Example for Go modules: https://github.com/aws/aws-sdk-go-v2/tags

**Comment by jetersen** [comment]
what does multiple tags solve if they point to the same commit sha of these tag?

**Comment by efectn** [comment]
> what does multiple tags solve if they point to the same commit sha of these tag?
> 
> Also looking at the linked repo each module has their own version number.
> 
> So your back to following the guardrail-dev example with multiple release drafter runs: https://github.com/guardrail-dev/guardrail/tree/master/.github

Thanks it seems better idea
