### ISSUE TITLE
I have some queries about VERION_RESOLVER

### ISSUE THREAD

**Issue by dh-Kang** [release-drafter/release-drafter#1215]
Hi.

I'm not usnig release-drafter yet. I'm trying to apply it.
I have some queries about VERSION_RESOLVER

1. My project release version. (e.g. v1.3.2)
And I want VERSION_RESOLVER can resolve version from v1.3.2. 
How can I config that?
2. VERSION_RESOLVER count labels.
How does it increase version?
For example, last version was v1.3.2 and 10 number of `patch` labeld PRs are merged.
When I tried merge to `main`, will VERSION_RESOLVER resolve the version with v1.3.12? or v1.3.3?
In case of 10 `minor`s and 4 `patch`es, will it be v1.4.0? or 1.13.0? or other version?

**Comment by jetersen** [comment]
It is always the next version that is resolved since the last release so `1.3.3`.

The template variable is `$RESOLVED_VERSION`

And you can configure it via the `.github/release-drafter.yml` config

It is documented here: https://github.com/release-drafter/release-drafter#version-resolver

You can see it used here: https://github.com/release-drafter/release-drafter/blob/06a49bf28488e030d35ca2ac6dbf7f408a481779/.github/release-drafter.yml#L26-L39

**Comment by dh-Kang** [comment]
> It is always the next version that is resolved since the last release so `1.3.3`.
> 
> It only bumps one version at a time, so if you have 10 PRs which match `minor` label selector then it would be `1.4.0`
> 
> Anything else would be very strange and lead to lots of jumping version numbers.
> 
> The template variable is `$RESOLVED_VERSION`
> 
> And you can configure it via the `.github/release-drafter.yml` config
> 
> It is documented here: https://github.com/release-drafter/release-drafter#version-resolver
> 
> You can see it used here:
> 
> https://github.com/release-drafter/release-drafter/blob/06a49bf28488e030d35ca2ac6dbf7f408a481779/.github/release-drafter.yml#L26-L39

Thank you for quick answer.
Actually my project version is not semantic. Its format is `major.minor.patch.revision`. there is one more dimension.
So, my project version is `1.03.02.00` exactly now.
Is it still resolving next version to `1.03.03.00`?

**Comment by jetersen** [comment]
Only if you input the version number via the action.

Release Drafter assumes semver as that is the library we use to bump version numbers.

**Comment by dh-Kang** [comment]
Thank you. I understand.

**Comment by dh-Kang** [comment]
I merged workflow and I'm testing. 
But always the version of draft is v.3.0.1.
How can I start this from v1.2.9 ?

**Comment by jetersen** [comment]
You maybe have a old tag/release that causes it misbehave.

**Comment by dh-Kang** [comment]
I solved my problem by editing version manually.
Thank you for support :)
