### ISSUE TITLE
How can I roll up changes between only production release

### ISSUE THREAD

**Issue by jonny7** [release-drafter/release-drafter#1222]
Hi

I'm enjoying using this, but I'm not sure how to achieve a correct change log between production releases. Currently my dev and rc releases contain all the changes. But I'd like to be able to roll all those changes up into a production release? Is that possible at all?

Thanks

**Comment by jetersen** [comment]
You can use multiple config files with `commitish: branchName`
or via action inputs
```
with:
  commitish: branchNamme
```

**Comment by jonny7** [comment]
Thank you!
