### ISSUE TITLE
Allow wildcard or regexp branch names in the config file

### ISSUE THREAD

**Issue by callmenick** [release-drafter/release-drafter#124]
## Problem

- repo's default branch is `development`
- repo's stable branch is `master`
- dev team bases off of `development`, works on a few features, bug fixes, etc
- team is ready to draft a release, so they open a new branch called `release/v1.0.10`, where the `v1.0.10` corresponds to the version of software they intend to release
- release drafter config file can't pick up the comparison and create the draft, as it only parses strings

## Proposed Solution

- make changes to the `triggerable-branch` script to read wildcards / regular expressions instead of just strings

@toolmantim looking at the `triggerable-branch` script, I think that's where the solution needs to be implemented, but if there's any suggestions you may have or quirks I need to be aware of, let me know! If you're cool with this feature addition, I can get cracking on it asap.

**Comment by toolmantim** [comment]
Adding pattern/wildcard/regex support to the branches option makes sense, and I think should work for you. Would happily accept a PR for it.

I believe the YAML parser supports regex? Alternatively you could implement our own ‘*’ string matching.

**Comment by callmenick** [comment]
Awesome, should be enough to get started. Thanks!

**Comment by callmenick** [comment]
That's awesome. I haven't had a chance to look yet, though I'd still like to if no one else gets to it.

**Comment by TimonVS** [comment]
If you're using GitHub Actions, it should be possible to achieve this with https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#onpushpull_requestbranchestags.
