### ISSUE TITLE
How should we handle "reverted" PRs ?

### ISSUE THREAD

**Issue by AllanOricil** [release-drafter/release-drafter#1257]
In the following pictures you can see that PR 762 was merged, then it was reverted by PR 763 and then added again with PR 765. How can I configure the release drafter to understand that "bugfix/MULE-3042" was actually added? I mean, in a way that it only appears once inside the "Bug Fixes" category?
![image](https://user-images.githubusercontent.com/55927613/197783510-aa2320e4-8e13-4fe8-b447-080cc2240720.png)
![image](https://user-images.githubusercontent.com/55927613/197783533-2207767f-4c11-4f4e-9bb3-95ec79f5608a.png)

**Comment by jetersen** [comment]
Use `exclude-labels` configuration and add a label to the PR.

All documented in the README.
https://github.com/release-drafter/release-drafter#configuration-options
