### ISSUE TITLE
Every time no changes

### ISSUE THREAD

**Issue by Drlanderf** [release-drafter/release-drafter#1259]
Hi !

I would like to use ur beautifull release drafter, but i think i'm doing something wrong or it's just a bug ? 

I made the workflow as he should, and i try to use the advanced config file but just two thing come :

name-template: 'v$RESOLVED_VERSION 🌈'

and

template: |
  ## Changes
  $CHANGES with no change while there were a lot of commits..

I try to force in my repo have some. change like bugfix or other but everytime, nothing come in release , the only one time who works (for $CHANGES) is was when i made another branch for dev and pull on the "main" but just "Dev (#67) @Drlanderf

u can found everything on my repo : 
https://github.com/Drlanderf/clara_oswald

thanks to help me to resolve the issue

I using release-it to make auto tag

**Comment by jetersen** [comment]
Release drafter uses pull requests to create release notes.

**Comment by Drlanderf** [comment]
> Release drafter uses pull requests to create release notes.

Ok, so it's my bad sorry, little question to use "categories" need the name of pull requestwith specific label like "bugfix", that don't take commit inside.. ?

**Comment by Drlanderf** [comment]
> > Release drafter uses pull requests to create release notes.
> 
> Ok, so it's my bad sorry, little question to use "categories" need the name of pull requestwith specific label like "bugfix", that don't take commit inside.. ?
Or do u have any repo with some example with how it work.. i'm sorry i'm lost about it, because before i was using auto changelog but it's not clean as this

**Comment by jetersen** [comment]
You can explore the GitHub releases here on release-drafter with links to each PR and see the labels.

Or explore some of the popular Jenkins plugins who actively use release-drafter.
https://github.com/jenkinsci/bom/releases

**Comment by Drlanderf** [comment]
![image](https://user-images.githubusercontent.com/30502847/199959622-90b8bfd2-e266-40ba-a176-d00e3e5c0701.png)
Don't really understand why my "🚀 Deploy new feature (https://github.com/Drlanderf/clara_oswald/pull/68) @Drlanderf" 
isn't into under "🚀 Features" title 

https://github.com/Drlanderf/clara_oswald/blob/release/.github/my-config.yml

**Comment by Drlanderf** [comment]
HO ! I'm really sorry to have opened an issue for so little.. I started using github recently in a clean way thanks a lot to ur help!
