### ISSUE TITLE
Pre-Release Changelogs - New Draft Releases has the same stuff like the pre release changelog

### ISSUE THREAD

**Issue by NavisGames** [release-drafter/release-drafter#1291]
Hello!

I got a little problem:
![image](https://user-images.githubusercontent.com/83245135/211051286-c2a26bf0-0565-44ab-8d76-80bc592ddc44.png)
![image](https://user-images.githubusercontent.com/83245135/211051496-c92ce729-b144-4579-ad67-bab2494e2d48.png)
in these images, the changelogs are pretty normal, because its not a pre release.

However if the Release is a Pre-Release, the Draft Release is copying the changelogs from the pre release in the draft.

Is there a way to "disable" this?

Here are another images to show what i mean:
![image](https://user-images.githubusercontent.com/83245135/211051856-5efb5897-d87c-474e-8813-4a147cfec755.png)
![image](https://user-images.githubusercontent.com/83245135/211051890-376b47a5-b308-488d-a370-49f282287a2a.png)

**Comment by NavisGames** [comment]
Mhh just looked at #1240 and it seems like its like that on purpose? Or do i dont understand it correctly ^^

**Comment by robbinjanssen** [comment]
I've created a pull request #1302 where you can config this behaviour. The default functionality will be the same as introduced by #1240
