### ISSUE TITLE
How to work with mono repo with multiple packages?

### ISSUE THREAD

**Issue by AllanOricil** [release-drafter/release-drafter#1294]
Could you give me an example of how to draft releases in a mono repo with the following structure

````bash
|_ packages
    |_ package_1
    |_ package_2
````

Packages are versioned separately using git tags. When deploying changes to "prod" a new tag is created to that particular package.

Maybe I can use a tag for each package? Is there a way to combine tags? like, if a PR has "package_1" and "feature" tags, then that PR change would be added to the "Package 1" release draft?

**Comment by jetersen** [comment]
https://github.com/guardrail-dev/guardrail/blob/master/.github/workflows/release-drafter.yml :)

**Comment by AllanOricil** [comment]
@jetersen how can I create a release draft that summarizes all packages that were released?
For instance, in a given release packages A and B were changed, therefore 3 release drafts were created:

1. package A release draft
2. package B release draft
3. repository release draft with the following format.

````
PACKAGES

(package_A)[link for the release draft of package A]
(package_B)[link for the release draft of package A]

````
