### ISSUE TITLE
Expose RESOLVED_VERSION As output field for using in the other steps

### ISSUE THREAD

**Issue by mehdihadeli** [release-drafter/release-drafter#1298]
Hi,
Is it possible to release drafter expose calculated version `$RESOLVED_VERSION` as [action output field](https://github.com/release-drafter/release-drafter#action-outputs)?
I want to this version inner my other steps.
I think it can be added to [existing outputs](https://github.com/release-drafter/release-drafter/blob/ac463ffd9cc4c6ad5682af93dc3e3591c4657ee3/index.js#L268)

**Comment by jetersen** [comment]
Pull request are welcome!

**Comment by mehdihadeli** [comment]
I've added it in this #1300 pull request

**Comment by ThiagoPanini** [comment]
Hi, any updates on this?

**Comment by inomn** [comment]
Hi! I have the same request. Any updates? Thanks.

**Comment by wax911** [comment]
Looking forward to this 😃
