### ISSUE TITLE
Create Release Draft Summary

### ISSUE THREAD

**Issue by AllanOricil** [release-drafter/release-drafter#1315]
continuing from this: https://github.com/release-drafter/release-drafter/issues/1294

## Description

Currently, developers can't easily find all release notes in a monorepo that creates multiple release notes at the end of a release. As an example:

https://github.com/guardrail-dev/guardrail

This issue happens because Github's main page can only display a single release notes as the latest. When multiple packages are released at once, developers must open the Releases view to find all release notes/packages that were released. This isn't pleasant when there are many package changes in a single release.

For instance, when the release shown below happened in the guardrail-dev repo, 2 releases notes were published. 

![image](https://user-images.githubusercontent.com/55927613/219375660-66036ecf-029b-4e94-b155-8c6545c1957b.png)

But as you can see in the next image, only one appears in Github's main page.

![image](https://user-images.githubusercontent.com/55927613/219374335-30412910-0851-47d1-952a-1f427be5dc93.png)

## Proposed solution

Automatically create a Release notes Summary, and mark it as the "latest" when multiple release notes are published for the same commit hash.

For instance, when packages A and B are released, 3 release drafts would be created:

1. package A release draft
2. package B release draft
3. release draft summary with the following format.

````
RELEASE SUMMARY 01-01-2023

The following packages were changed in this release:

[package_A](https://github.com/OWNER/REPO/releases/tag/package_A-v1.0.0)
[package_B](https://github.com/OWNER/REPO/releases/tag/package_B-v1.1.0)

```` 

Because the release notes summary would be accessible straight away from Github's main page, developers would be able to quickly find all packages that changed in the latest release.

The title of this release could default to `<release_date>`, `Latest Release`, `Release Summary <release_date>`.  And this release summary must be configurable.

````yml
...
create-release-draft-summary: true
release-draft-summary
    make_it_latest: true
    template
        ...
````

## Workaround
Someone has to create a release notes at the end of the release and mark it as the latest.

**Comment by blast-hardcheese** [comment]
This is a neat idea, the only comment I'd offer is that not every package gets released on the same release cadence, so the copy `RELEASE SUMMARY 01-01-2023 ` and `The following packages were changed in this release:` don't apply in all cases.

I'd say that a summary in the structure of:

```
Latest Releases
===

- [foo-v0.1.2](...)
- [bar-v1.2.3](...)
- [baz-v2.3.4](...)
```

would make sense and not be too _terribly_ difficult.

Something that may be unpleasant is the process of un-releasing the "Latest" release only to replace it with a new "Latest". If this were not done, there'd be a lot of garbage in the way of random metadata releases that don't do too terribly much once they age out.

Additionally, if you have any actions that get triggered `on: release` those would have to explicitly filter out these non-release releases.

This is a great idea for usability though!
