### ISSUE TITLE
Configuration file is not found

### ISSUE THREAD

**Issue by justinmchase** [release-drafter/release-drafter#1324]
> Invalid config file { name: 'event', id: '4318991515', stack: 'Error: Configuration file .github/release-drafter.yml is not found. The configuration file must reside in your default branch.

I have the file in the `.github/.github/release-drafter.yml` at the org level but not in the individual repos (they all have the same settings), so why is it failing? Why should it need the file in the repo if there is a totally valid one at the org level?

> Release Drafter also supports [Probot Config](https://github.com/probot/probot-config), if you want to store your configuration files in a central repository. This allows you to share configurations between projects, and create a organization-wide configuration file by creating a repository named .github with the file .github/release-drafter.yml.

So does it also need an empty one in each repo or something? Why am I seeing this error?

![image](https://user-images.githubusercontent.com/10974/222627226-7e9767c2-8664-4649-a0c9-5ab7baffe52d.png)

**Comment by justinmchase** [comment]
The file is definitely there at the org level, yet it still can't find it.

![Screen Shot 2023-03-02 at 9 52 56 PM](https://user-images.githubusercontent.com/10974/222628926-00201d4f-a35a-4a51-8fa2-9f6ebd3085eb.png)

![Screen Shot 2023-03-02 at 10 06 21 PM](https://user-images.githubusercontent.com/10974/222628939-0cbe7d95-7cb1-44a9-9a38-fe9c07588d25.png)

**Comment by jetersen** [comment]
Since your taking screenshots I assume your `.github` repo is not public. So you need to you have two options make the .github public which is actually required for other features of the .github repo to work.

Or provide a PAT to resolve access between repos.

**Comment by justinmchase** [comment]
Yes its enterprise and its set to `internal`, but not `private`. 

Do you think that this would be sufficient rather than a PAT? Which I don't think I'm going to be able to make easily for all the repos in the org.

```yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by justinmchase** [comment]
Actually I see I have already configured it this way and it doesn't work. What a huge bummer.

**Comment by justinmchase** [comment]
Seems to be related to this thread:
https://github.com/actions/setup-node/issues/49

I'll close this for now since that seems to be the answer.

**Comment by JoshuaTheMiller** [comment]
In case this proves helpful for others- at least within GitHub Enterprise (server/cloud), you can allow Actions from other repositories to read a specific repository. This can be done by performing the following steps:

1. Go to the repository that you want a GitHub Action to `read`
2. Go to `Settings` --> `Actions` --> `General`
3. Select the proper `Access` setting based on your needs

![image](https://user-images.githubusercontent.com/4266541/222724844-f7245fc9-f6b7-416d-bb72-692ff7a94d43.png)
