### ISSUE TITLE
Increase prerelease without prerelease identifier 

### ISSUE THREAD

**Issue by bheemvennapureddy** [release-drafter/release-drafter#1366]
Our use case is 

- Draft a prerelease with regular semantic versions v1.1.0 ( release candidate )
- Run test either via automation or manual if this pass go to prod update prerelease to latest 
- If tests fail create a new release candidate which should be an increment from prevoious pre release which is not the case with prerelease identifier set to empty 

Issue duplicate draft tags with prerelease.

<img width="572" alt="Screenshot 2023-10-24 at 11 59 35 AM" src="https://github.com/release-drafter/release-drafter/assets/144472943/6abb8986-64f0-4d52-8810-61f438af29e9">

Is there a way we can increment prerelease without any identifier ?

**Comment by jetersen** [comment]
Your workflow would include promotion of the v1.1.0 to release from pre-release? Or do you intend to force push the v1.1.0 tag with fixes?
How about changing your pre-release to include a pre-release identifier?
Release drafter is behaving as intended. It will ignore pre-releases to create a full draft for a given release.

**Comment by bheemvennapureddy** [comment]
> Your workflow would include promotion of the v1.1.0 to release from pre-release? Or do you intend to force push the v1.1.0 tag with fixes?

Our intention is to promote v1.1.0 to latest ( prod release ) from prerelease but there were road blocks on the way with either infra or testing , so we want a new draft which is a increment from the previous draft has all the changes along with a fix.

So the next prerelease draft should be v1.1.1 or v1.2.1 either one of these

**Comment by bheemvennapureddy** [comment]
> Release drafter is behaving as intended. It will ignore pre-releases to create a full draft for a given release.

Apart from including a prerelease identifier i don't see a way to work around this.

**Comment by jetersen** [comment]
https://github.com/release-drafter/release-drafter#configuration-options did you check out ?
Perhaps `include-pre-releases` is what you are looking for?

**Comment by bheemvennapureddy** [comment]
@jetersen makes sense that sounds about right - if i do so the change log is not pulling up all the log from previous pre-release which kind of makes sense 
<img width="998" alt="Screenshot 2023-10-25 at 11 04 52 AM" src="https://github.com/release-drafter/release-drafter/assets/144472943/213113df-c54e-44ba-89d9-faa2142a59b8">

**Comment by bheemvennapureddy** [comment]
Sorry there was a typo.
