### ISSUE TITLE
GraphqlResponseError: Release drafter suddenly broke

### ISSUE THREAD

**Issue by caffeine-addictt** [release-drafter/release-drafter#1389]
Hey! Release drafter has been really helpful so far, but it suddenly broke recently 🤔 

You can find the logs here:
https://github.com/caffeine-addictt/template/actions/runs/8987053379/job/24684602587
https://github.com/caffeine-addictt/template/actions/runs/8986814209/job/24684105248
![image](https://github.com/release-drafter/release-drafter/assets/104479537/0c6f84c4-6d3e-47d0-9f24-7da08177daa6)

Additional stuff:
- I am using v6
- Workflow file [here](https://github.com/caffeine-addictt/template/blob/main/.github/workflows/draft-release-tag.yml)
- It is failing consistently for my 3 most recent `v1.10.0`, `v1.11.0` and `v1.11.1` releases.

Would appreciate any help or ideas in resolving this! Thanks.

**Comment by Nizar12n** [comment]
[SSH](url)

**Comment by caffeine-addictt** [comment]
Looks like it finally did draft something randomly.
I'll leave this issue up until I can confirm that it is working on my next iteration.

**Comment by caffeine-addictt** [comment]
I can confirm it is now working as expected! See [this](https://github.com/caffeine-addictt/template/releases/tag/v1.11.2) release. 🥳 

Not a clue why the error even occurred in the first place, but since I am no longer experiencing this, I'll go ahead and close this issue. :>
