### ISSUE TITLE
Auto-publish release feature

### ISSUE THREAD

**Issue by rnorth** [release-drafter/release-drafter#141]
Since #91 we've been able to get many of our repos using release drafter, with a nice Releases page and automatic patch version bumps. Thanks again for this tool!

One additional feature that we'd be really interested in contributing is automatic _publication_ of releases. For many of our repos we typically want to release a new version after each PR is merged.

I thought of creating a separate probot to do this in the spirit of separation of concerns. However there is no hook for 'draft release created'; Release Drafter, as the creator of the draft release, is really in a unique position of being able to do this.

So I'd like to propose adding a feature that would:

- be _opt-in_ via a new config flag
- require a template for release tag and name
- automatically publish a release after it has been created
- ... if/unless some configurable label is present on the just-merged PR

I'd be keen to get your thoughts on this!

**Comment by toolmantim** [comment]
Oh gosh, then we’re going to have to rename it 😁

I think it’s worth a spike to see what it’d take to make it happen! And see how it affects the config, readme and code?

**Comment by ostrolucky** [comment]
Yes please!

**Comment by JimNero009** [comment]
Always been quite interested in this, and have started work here: https://github.com/toolmantim/release-drafter/pull/304

**Comment by JimNero009** [comment]
It doesn't work quite in the way Richard suggested, but happy to be persuaded to change the underlying philosophy.

**Comment by TimonVS** [comment]
Awesome idea!

> I thought of creating a separate probot to do this in the spirit of separation of concerns. However there is no hook for 'draft release created'; Release Drafter, as the creator of the draft release, is really in a unique position of being able to do this.

It's been awhile since this issue was opened, in the meantime GitHub Actions has been released which makes it possible to execute logic after Release Drafter is done creating or updating a draft. The next release will include a fix for https://github.com/release-drafter/release-drafter/issues/326 which should make it possible to create this in a separate Action.

**Comment by orcutt989** [comment]
Has the publish functionality been implemented?

**Comment by jetersen** [comment]
Should be doable with both #513 and #424
Though #472 might be needed in some cases.

**Comment by jetersen** [comment]
There is still work to do for auto release as we currently do not work on tags.

Version-resolver and publish gets really close but can only be done on the `branches` config. Which is a huge limiting factor.
I'll do my best to resolve the current issue.

**Comment by jetersen** [comment]
@rnorth how do you vision the release workflow from release-drafter?

Would it be based on a certain label like #519 ?
Or is it when you push a tag?
Or when you create a release from GitHub?

I would be open to a video discussion to ping-pong ideas faster :)

**Comment by jetersen** [comment]
Properly best off waiting for #546 it should allow any desired release workflow from GitHub action.
