### ISSUE TITLE
Release Drafter Stopped Working After Last Commit

### ISSUE THREAD

**Issue by usmandap** [release-drafter/release-drafter#1414]
https://github.com/release-drafter/release-drafter/commit/1a8019e4c8fec5c7b883897bf4425c61b0b63971

Right after this commit I can see the release drafter have stopped working for me. It is unable to push any new releases for me.

**Comment by jetersen** [comment]
I don't see how that has anything to do with that commit.
Also this build that uses release drafter works just fine:
https://github.com/release-drafter/release-drafter/actions/runs/11631906061/job/32393923479
https://github.com/release-drafter/release-drafter/actions/runs/11265075599/job/31326272502

**Comment by jetersen** [comment]
Without more information, I can't assist
