### ISSUE TITLE
How to configure this with gitflow?

### ISSUE THREAD

**Issue by thibmaek** [release-drafter/release-drafter#175]
I tried, really. But I didn't find a way to create the release.

Our repo has base branch set to develop, but I only want to create releases for code ending up on master.

Relevant Release Drafter config: https://github.com/inthepocket/hubble-scripts/blob/develop/.github/release-drafter.yml

Tried first with merging remotes into master and pushing, then tried to merge via PR from develop to master, but the release is not showing up as a Draft when I go to the releases tab.

![image](https://user-images.githubusercontent.com/6213695/55890684-72836c80-5bb3-11e9-9841-fece289c705b.png)

**Comment by casz** [comment]
Change your default branch to master?

Or perhaps we should provide a way to override the default branch.

**Comment by thibmaek** [comment]
That would mean all the PRs point at master by default and checking out the repo across team members starts from master. Kind of defeats the purposes of gitflow I think

**Comment by sullimander** [comment]
We would need the ability to set the release branch separate from the github default branch in order for us to use it.

**Comment by TimonVS** [comment]
Can you walk me through the issue you're having in a little more detail? I can see that you used the `branches` option in your config, why doesn't that give the desired result?

**Comment by StewartSnow** [comment]
Hey we have the same issue here - we follow gitflow and would prefer that all draft releases are created on the master branch, rather than default develop branch (as is common under gitflow). 
An additional config entry to indicate the branch that the release / tag should be drafted on would be most helpful.

**Comment by thibmaek** [comment]
This is indeed the same problem I am encountering

**Comment by rvanlaak** [comment]
In our gitflow-like scenario we have `master` setup as `develop`, and `production` as `master. What we see happening, is that release drafter nicely creates drafts for `master`. 

A problem we have (that sounds similar to the issue description) happens in the following scenario: 

1 - A release branch gets created, testing starts and could take several days
2 - PRs that in the meanwhile get merged in `master` (read: the gitflow develop) and do not make the release - as they are not in the release branch.
3 - The release branch gets merged in `production` (read: the gitflow master) and gets tagged.

The actual problem that happened in the meanwhile: the PRs that get merged in step 2 do not appear in the next release draft.

**Comment by mkurz** [comment]
I think the problems you are facing can be solved with the `filter-by-commitish` config, I came up with this comment on how to change the `target_commitish` of a GitHub release.

**Comment by mkurz** [comment]
You also might be interested in #1061
