### ISSUE TITLE
Support commit message description

### ISSUE THREAD

**Issue by jetersen** [release-drafter/release-drafter#186]
Add support for including the commit message's `description`

I specifically created [casz/no-merge-description-extension](https://github.com/casz/no-merge-description-extension)
to avoid GitHub's default behavior when merging pull requests.

Would be useful in cases like this https://github.com/jenkinsci/configuration-as-code-plugin/commit/850bfa40ac864c8c63a8d4983ad1b75f3d9562c6

The description could be inside `<!-- -->` as an aide to the release author.

**Comment by toolmantim** [comment]
I guess some people might want to include the pull request description in the release notes. Personally I open the things in new tabs from the preview window.

I couldn't quite figure out from the linked commit what you mean exactly, for when it would be helpful?

**Comment by casz** [comment]
```
Remove matrix-auth from support plugin (#845)

Moved to `matrix-auth` in 2.4
```

I would like for `Moved to `matrix-auth` in 2.4` not to be omitted from the changelog :sweat:

**Comment by casz** [comment]
And no I don't want pull request description, that only leads to a nightmare when you use GitHub templates.

**Comment by TimonVS** [comment]
> The description could be inside `<!-- -->` as an aide to the release author.

> And no I do not want pull request description, that only leads to a nightmare when you use GitHub templates.

Just an idea, we could use the PR description and extract only a comment from it like:

```html
<!-- RELEASE_NOTES:START -->description here<!-- RELEASE_NOTES:END -->
```

That or we can add a `$COMMIT_DESCRIPTION` variable and add a custom replacer that will make it work for your usecase (description inside `<!-- -->`).

**Comment by toolmantim** [comment]
Ah, I see… not the PR description, but the commit description! I feel including the description by default might not be great, only because people can put quite long, ASCII-formatted essays in commit descriptions.

But I'm curious how you might want this to be output? (and configured?) Would it be something like this?

```yml
change-template: '- $TITLE @$AUTHOR (#$NUMBER)<br>$DESCRIPTION'
template: |
  ## Changes

  $CHANGES
```

Which would generate:

```yaml
## Changes

* Remove matrix-auth from support plugin @casz (#845)<br>Moved to `matrix-auth` in 2.4
```

This would mean a new `$DESCRIPTION` field in the `change-template`.

**Comment by leikoilja** [comment]
@toolmantim that would be amazing to be able to include a short PR description in the bullet point. The idea from @TimonVS sounds really amazing to be able to just have a short part of PR description being included here.
With a use of some sort of tags, just like: 
```
<!-- RELEASE_NOTES:DESCR_START -->Short description from PR body<!-- RELEASE_NOTES:DESCR_END -->
``` 
And config:
```yml
change-template: '- $TITLE @$AUTHOR (#$NUMBER)<br>$DESCRIPTION'
template: |
  ## Changes

  $CHANGES
```
Having an end result being as:
![image](https://user-images.githubusercontent.com/10655107/131973958-9cee7caa-bfb5-4fd3-af5a-043eae3da9d4.png)

**Comment by jetersen** [comment]
Added support for body in #531
