### ISSUE TITLE
Release Target Setting

### ISSUE THREAD

**Issue by nchudleigh** [release-drafter/release-drafter#203]
Would be really helpful if the Release Draft Target (optionally) was the latest commitish.

The two issues with using Master as the Target are:
1. PR merged to master in the time that someone is viewing the draft, the merged PR will not be documented on the release. 
2. If the release is modified to link to another tag, the tag will actually mark the current state of master.  So a release candidate, beta, or staging process has the potential to break.

It is a fairly easy thing to automate (https://developer.github.com/v3/repos/releases/#create-a-release)
![image](https://user-images.githubusercontent.com/5580824/57237599-8d4fd200-6ff5-11e9-8964-da7aff51bd1e.png)

If this gets a :+1: I can write and submit this PR myself!

**Comment by toolmantim** [comment]
Thanks, sounds sensible. Any ideas for a configuration setting name?

Also, possibly related to #175?

**Comment by nchudleigh** [comment]
No strong feelings on that, off the top of my head, `target` with configurable types as the value feels pretty clean and expandable.

```yml
target: 'branch' # this would be the default setting as it is now
target: 'commit' # this would target the latest commit to the branch
```
The only downside is this doesnt tie too nicely into the branches array that exists on the config currently, as you cannot specify a different setting per branch.

Without revisiting that though you would be introducing conflicting config.  Let me know what you think :)

**Comment by nchudleigh** [comment]
@toolmantim Any further thoughts on this?

**Comment by casz** [comment]
I would just perhaps just look for the last few tags and find one that matches `tag-template`

**Comment by nchudleigh** [comment]
@casz On the implementation side this is pretty trivial yeah. 

More so asking for input on the settings. Do you have any thoughts on that?

**Comment by casz** [comment]
This becomes rather complex as soon as you run anything besides trunk-based development.

you want the YAML syntax to both support `branches` and `tags` both in wildcard format.
Then to further complicate you want the find a commitish target based on the `tags` pushed and hopefully they match your `tag-template`
To complicate it, even more, you most likely want it to support multiple `tag-templates`
To absolutely further complicate it, you really want to support creating release-draft for multiple branches and multiple tags independent of each other.

**Comment by jetersen** [comment]
Hmm the recent changes to master and the fact that we have `$RESOLVED_VERSION` see use case below or see the readme about [version-resolver](https://github.com/release-drafter/release-drafter#version-resolver):

https://github.com/release-drafter/release-drafter/blob/6b5b16358bd49becf320405ee92143d11dcb6869/.github/release-drafter.yml#L1-L34

**Comment by jetersen** [comment]
Once #545 is solved this should also give you more freedom!

**Comment by mkurz** [comment]
Maybe this helps someone: https://github.com/release-drafter/release-drafter/issues/656#issuecomment-806184887
