### ISSUE TITLE
Incorrect timestamp is used when drafting

### ISSUE THREAD

**Issue by jetersen** [release-drafter/release-drafter#222]
@TimonVS seems that the GraphQL is using the date from the tag/release when it was created instead of using the date from when the tagged commit was created. That way, not all PRs will show :cry: 

https://github.com/jenkinsci/accurev-plugin

![image](https://user-images.githubusercontent.com/1661688/58435699-02c53480-80c2-11e9-9d58-49443e04aff7.png)
![image](https://user-images.githubusercontent.com/1661688/58435726-3738f080-80c2-11e9-9d1c-64a749e348f9.png)

**Comment by casz** [comment]
The latest release was created after merging `#67,68,70`

**Comment by TimonVS** [comment]
If I understand correctly, v0.7.19 was using an older commit as a target when the release was created?

**Comment by casz** [comment]
yes 0.7.19 was tagged on this commit: https://github.com/jenkinsci/accurev-plugin/commit/22689d772229be7d4c9885e3060904303650225b dating back to Jan 22, 2019, 10:52 AM GMT+1

**Comment by casz** [comment]
it is probably unrelated to GraphQL now that I think about.

I'd say it's still a "bug" it is using the date from the "latest" release instead of taking the date from the latest released tag :sweat:

**Comment by TimonVS** [comment]
How do you propose we fix this? Should we use the date of the tagged commit?

**Comment by casz** [comment]
For me using the tagged commit's date if available otherwise default to release's date, makes the most sense.

**Comment by casz** [comment]
I'll try and get to this tonight. Unless your faster @TimonVS 😅

**Comment by TimonVS** [comment]
You can take this one if you'd like, the next issue I'll work on is #139, but I'll do that next week :)

**Comment by mangolas** [comment]
Has there been any work done on this yet? We stumbled on this problem as well on our release automation work. Tag would be better source of truth for change calculation than release date.

Why commits are searched with dates to begin with? Wouldn't it be better to use releases tag sha to calculate changed commits?

**Comment by casz** [comment]
@mangolas no I never got time to fix it.

Yes it would make more sense to use last release tag sha to calculate changes.

**Comment by mangolas** [comment]
Ok, looks like one would only need to figure out how to change `findCommitsWithAssociatedPullRequestsQuery` at https://github.com/release-drafter/release-drafter/blob/36d7384e147b7cc02b55be4cc799f30e96c5e1fd/lib/commits.js#L5

**Comment by mangolas** [comment]
I tried to fix this. Looks like for sha based solution one would need to use git to do it, or at least I couldn't figure out how one could do it using GraphQL.

**Comment by casz** [comment]
Here is a quick way of getting the commit sha from the object/tag
```graphql
query { 
  repository(owner: "release-drafter", name: "release-drafter") {
    object(expression: "v5.2.0") {
      oid
      ... on Commit {
        oid
        history(first: 100, since: "2018-06-22T04:37:29Z") {
          nodes {
            oid
            messageHeadline
            author {
              user {
                login
              }
            }
            committedDate
          }
        }
      }
    }
  }
}
```

**Comment by mangolas** [comment]
Thanks, what I meant is that after one has tag sha in hand, how one could utilise it in order to limit pr history query as it only has 'after' and 'until' parameters.
