### ISSUE TITLE
Automatic name draft releases according to labels

### ISSUE THREAD

**Issue by Remzi1993** [release-drafter/release-drafter#256]
I follow semver and I would like to have release drafter draft releases accordingly.
If features are added $MAJOR.$MINOR.$PATCH only the minor should be bumped.

Is there a way to automate the version name to such an extent?

Kind regards,
Remzi

**Comment by casz** [comment]
I suggest you read the readme again 😕

**Comment by casz** [comment]
Hint: https://github.com/toolmantim/release-drafter#next-version-variables

**Comment by Remzi1993** [comment]
I couldn't get this to work, only $PATCH version gets bumped all the time.

**Comment by Remzi1993** [comment]
@casz This is my template, see: https://github.com/Remzi1993/jquery-manager/blob/master/.github/release-drafter.yml

What do you suggest I should add or change?

**Comment by casz** [comment]
```yml
name-template: 'jQuery Manager v$NEXT_MINOR_VERSION'
tag-template: '$NEXT_MINOR_VERSION'
```

**Comment by Remzi1993** [comment]
Hi @casz 

Thank you so much, I didn't saw that.
Is it possible to make this more automatic, for example connecting this with labels.

## For example
name-template: 'jQuery Manager v$NEXT_VERSION'
tag-template: '$NEXT_VERSION'

$NEXT_VERSION = $NEXT_{PATCH,MINOR,MAJOR}_VERSION
$PATCH = labels: Fix, Bug, Security, Library, etc
$MINOR = labels: Feature

Is this possible or something like that?

**Comment by casz** [comment]
if you would read the readme you would know? 😕

But no you cannot.

**Comment by Remzi1993** [comment]
@casz thank you so much for release drafter. This is more like a feature request / something to think of.
Maybe in the distant future 😉

**Comment by casz** [comment]
Feel free to contribute 😉

**Comment by jetersen** [comment]
We have a new variable `$RESOLVED_VERSION` Which does exactly this.
See the readme about [version-resolver](https://github.com/release-drafter/release-drafter#version-resolver)

**Comment by jetersen** [comment]
Or actually see our use case here on release-drafter: 
https://github.com/release-drafter/release-drafter/blob/6b5b16358bd49becf320405ee92143d11dcb6869/.github/release-drafter.yml#L1-L34
