### ISSUE TITLE
deprecated HCL syntax in GitHub Actions

### ISSUE THREAD

**Issue by paveg** [release-drafter/release-drafter#276]
Hi, there.

I saw the article, and I tried to apply yaml syntax to my [repo](https://github.com/paveg/oura/tree/master/.github/workflows) but it doesn't working.

> GitHub Actions now uses YAML syntax in workflow files. Support for the HCL syntax in GitHub Actions will be deprecated on September 30, 2019. To continue using workflows that you created with the HCL syntax, you'll need to migrate the workflow files to the new YAML syntax using the migration script.

ref: [migrating-github-actions-from-hcl-syntax-to-yaml-syntax](https://help.github.com/en/articles/migrating-github-actions-from-hcl-syntax-to-yaml-syntax)

Please make sure.

**Comment by TimonVS** [comment]
Has been fixed some time ago :). Thanks for reporting!
