### ISSUE TITLE
'Rollback' releases

### ISSUE THREAD

**Issue by JimNero009** [release-drafter/release-drafter#280]
Hi!
I've been working on adding some functionality to release drafter to 'rollback' a release if a later CI system calls back to Github to mark something as failed. I've got some code on a branch here https://github.com/JimNero009/release-drafter/tree/unrelease-fork.

You can see the basic idea in https://github.com/JimNero009/release-drafter/blob/unrelease-fork/lib/undo.js#L5 -- this function runs on 'status' events, and deletes tags and puts releases back into draft states if there is a status failure.

Would you be interested in adding this kind of thing at all?

Cheers,
Jim

**Comment by TimonVS** [comment]
Hey Jim, sorry for the late reply.
Great idea and thanks for working out a prototype. This is not something we currently want to add to Release Drafter as that would broaden the scope a little too much, we want to focus on the generation of changelogs and not the release process itself per se. I do think this could be an awesome GitHub Action to build :)
I'm closing this issue for now, but do let me know if you have any further thoughts on this!

**Comment by JimNero009** [comment]
Fair enough! Thanks for taking the time to look.
