### ISSUE TITLE
Document the Release Drafter JSON Schema

### ISSUE THREAD

**Issue by oleg-nenashev** [release-drafter/release-drafter#311]
I am working on adopting Release Drafter in Jenkins on the organization level. One of the obstacles we hit is that wrong changes in https://github.com/jenkinsci/.github/blob/master/.github/release-drafter.yml break the Release Drafter logic entirely. So we would like to setup some CI for the instance which would verify Release Drafter.

In order to do so, it would be great to have a Schema file for the Release Drafter configuration. IMHO it could be put directly in this repository and then versioned through GitHub releases.

**Comment by casz** [comment]
Schema work was done in https://github.com/toolmantim/release-drafter/pull/193

**Comment by oleg-nenashev** [comment]
OK, now it is about documentation @casz

**Comment by casz** [comment]
if we publish it on http://schemastore.org/json/ it should work flawlessly.

Once #193 is merged we can send a PR for adding release drafter to the schemastore :)

**Comment by casz** [comment]
This is released on the schemastore. Your VSCode (requires [redhat.vscode-yaml](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml)) or any editor that integrates with schemastore should provide the schema definition.

**Comment by casz** [comment]
Not sure what else you want from documentation :) You can always point directly to the JSON schema: https://raw.githubusercontent.com/release-drafter/release-drafter/master/schema.json

**Comment by casz** [comment]
There might be a need to escape the defaults as change-template comes out as `change-template: *  (#) @` 
https://github.com/release-drafter/release-drafter/blob/5e307e1c8f08c923e0ae855e21a6faf64bce12ea/schema.json#L15

**Comment by jetersen** [comment]
This is done. Part from the bug reported to vscode-yaml. So lcosing
