### ISSUE TITLE
Allow loading config from an URL

### ISSUE THREAD

**Issue by ssbarnea** [release-drafter/release-drafter#319]
Instead of adding the release-drafer.yml file to each repository, it would be better if we could configure the action to load the configuration from a specific centralized location, mainly a URL. This would allow us to avoid a lot of boring maintenance work across repositories.

I maintained around a dozen open-source packages and I did not see any need to use different formats across them. 

Should I also mention that implementing this would likely help people adopt a more standardized format?

**Comment by casz** [comment]
You can create an .github repo for org or user that it allows you to to merge the two.

See https://github.com/jenkinsci/.github/blob/master/.github/release-drafter.yml

**Comment by casz** [comment]
Here it is used 
https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/.github/release-drafter.yml

**Comment by TimonVS** [comment]
What @casz should work. For more information on the possibilities, you can refer to the [probot-config docs](https://github.com/probot/probot-config). We should probably add a mention to this in the config :)

**Comment by ssbarnea** [comment]
Apparently few things are missing from the `_extend` approach:

* You still have to add a `.github/release-drafter.yml` file with a single line on each repository, no much economy of scale here
* To enable running the action, you still have to create a `.github/workflows/release-drafter.yml` file which contains a hardcoded version of the action (if updates appear, these actions will also need to be update)

Is there a better way to do this where I can avoid these manual steps, making easy to enable the release drafter on each repo in a way that does not need additional tuning?

I did look at https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/sharing-workflows-with-your-organization which documents on how to create template actions. Still these would be really effective if we can avoid having to create the "extend" redirect files or the versioning.

I suppose that for versioning using `@latest` should work, with the small risk of getting broken by a major release. Still, fixing it would likely be done by touching a single repository instead of... all.

IMHO, `config-name` argument should allow mentioning the centralized config.

**Comment by ebebbington** [comment]
@ssbarnea fyi use a `dependabot.yml` inside `.github` for updating action versions

**Comment by jetersen** [comment]
With the latest release you can add inside your `.github` a single `.github/release-drafter.yml` that the GitHub action will pickup. You are no longer required to have `_extends` inside `.github/release-drafter.yml` on a repository!

I would consider that good enough. So closing.
