### ISSUE TITLE
Support for sorting PRs by the title

### ISSUE THREAD

**Issue by ryamaguchi0220** [release-drafter/release-drafter#323]
In my use case, I'd like to sort PRs by `title` instead of `merged_at`.
I think it makes sense to add a `sort-by` option that accepts either `title` or `merged_at` so that users can decide for themselves what they like best.

**Comment by TimonVS** [comment]
Hey @ryamaguchi0220, thanks for creating a PR for your issue!
Could you perhaps elaborate on why you want to sort the changelog by title? I am very careful about adding new configuration options since we already have so many, and it's hard to remove once people are using it actively.

**Comment by ryamaguchi0220** [comment]
@TimonVS  Thank you for your response!

> why you want to sort the changelog by title?

I think this feature has two merits

* Improve readability of the changelog by grouping the changes by their scope

In my project, each PR include scope that indicate place(e.g, API names) of the change in its title. 
So, sorting the changelog by title would makes it easier for users to find changes about scope that they are interested in.

This is readable
```
✨New features

・[Scope A] blablabla
・[Scope A] blablabla
・[Scope B] blablabla
・[Scope B] blablabla
・[Scope C] blablabla

🐛Bug fixes

・[Scope A] blablabla
・[Scope A] blablabla
・[Scope B] blablabla
・[Scope B] blablabla
```

This is not readable...
```
✨New features

・[Scope B] blablabla
・[Scope A] blablabla
・[Scope C] blablabla
・[Scope A] blablabla
・[Scope B] blablabla

🐛Bug fixes

・[Scope A] blablabla
・[Scope B] blablabla
・[Scope B] blablabla
・[Scope A] blablabla
```

* Improve readability of the changelog by sorting by what users know and are interested in

My project users don't know and are not interested in when PRs were merged.
It means that users can not figure out what the changelog is sorted by and it would worsen its readability.

**Comment by TimonVS** [comment]
Those are both excellent points. I'm convinced that this configuration option is desirable, so I'll be merging it and create a new release.

**Comment by TimonVS** [comment]
It has been released in https://github.com/release-drafter/release-drafter/releases/tag/v5.3.0 :)

**Comment by ryamaguchi0220** [comment]
Thanks for the release!
