### ISSUE TITLE
prerelease option

### ISSUE THREAD

**Issue by julianladisch** [release-drafter/release-drafter#332]
Currently release-drafter creates all draft releases with the default "prerelease: false".
It would be nice if there were a prerelease configuration option that defaults to false but can be set to true so that release-drafter creates draft releases with "prerelease: true".

**Comment by TimonVS** [comment]
Great suggestion. We'll be implementing this soon.

**Comment by pdcmoreira** [comment]
@TimonVS I was actually trying to implement that myself, together with the ability to specify a custom config name (I can give you a use-case where that can be very useful, if you want):
https://github.com/release-drafter/release-drafter/compare/master...pdcmoreira:support-prerelease

**Comment by TimonVS** [comment]
This has been released in [v5.5.0](https://github.com/release-drafter/release-drafter/releases/tag/v5.5.0).
