### ISSUE TITLE
run action without docker

### ISSUE THREAD

**Issue by jetersen** [release-drafter/release-drafter#358]
I'd like to drop the need for running the action inside a docker container.

_Originally posted by @casz in https://github.com/release-drafter/release-drafter/issues/335#issuecomment-569700969_

**Comment by TimonVS** [comment]
Yup. We can use https://github.com/probot/actions-adapter to make that happen.

**Comment by casz** [comment]
That might be a quick fix.

I was thinking we would have two entry points to handle both probot and actions code.

**Comment by casz** [comment]
I tested out the two approaches mentioned in the probot-actions-adapter readme.

Vendor node_modules which add nearly 1.810.297 additions
or using @zeit/ncc which adds only 127.125 additions

Not sure either one is better.

See
https://github.com/casz/release-drafter/tree/chore/probot-adapter
https://github.com/casz/release-drafter/tree/chore/probot-adapter-node-modules

**Comment by casz** [comment]
Hmm not sure why, vendoring seems incomplete: https://github.com/casz/test-release-drafter-action-adapter/runs/380278004

This is testing with node_modules vendoring which seems to fail.

**Comment by casz** [comment]
Ah we cannot use yarn to for vendoring our node_modules.

So the question becomes to we want to switch to npm and package-lock.json or use `@zeit/ncc` to stay with yarn?

**Comment by casz** [comment]
Hmm @TimonVS @toolmantim 

I been thinking about converting the project to typescript. Add lerna to manage release-drafter/core, release-drafter/action, release-drafter/probot

Using https://github.com/actions/typescript-action as a base for release-drafter/action
With this we could potentially not deprecate release-drafter/probot?

As to those using release-drafter/probot be it GitHub enterprise or not can continue using it.
I was even thinking about providing a release-drafter/probot-monitor that would use Github OAuth to provide access to logs for the repos they have "write/(maintainer?)" access to.

**Comment by TimonVS** [comment]
That sounds like a solid idea @casz! Also really like the idea of `release-drafter/probot-monitor` as that would solve one of the biggest problems we were having with GitHub Apps: the missing logs. Is there anything you need from me to get this started?

**Comment by ajcann** [comment]
I'd be excited to see this. I've been writing pure js actions and ncc and have love how fast they start and run.

**Comment by casz** [comment]
We already have a PR with ncc #376
