### ISSUE TITLE
Can't find "template" in yaml even when present.

### ISSUE THREAD

**Issue by tayyab-anwar** [release-drafter/release-drafter#398]
I have the following release-draft.yml:
<img width="996" alt="Screen Shot 2020-01-27 at 11 00 23 AM" src="https://user-images.githubusercontent.com/58931172/73153078-3b575b00-40f4-11ea-94d0-f8fc53c9ce7b.png">

In this, I have specified my config file as release-config.yml. Here is a screenshot of that:
<img width="1008" alt="Screen Shot 2020-01-27 at 11 01 33 AM" src="https://user-images.githubusercontent.com/58931172/73153120-65108200-40f4-11ea-9260-824ecf7a6109.png">

However, when the action runs, I always get the same error:
<img width="813" alt="Screen Shot 2020-01-27 at 11 02 12 AM" src="https://user-images.githubusercontent.com/58931172/73153151-7bb6d900-40f4-11ea-808d-2d87be484c78.png">

My project does not have a release-drafter.yml confiig file. It's somehow still opening that file and giving me the "template" prop not found message. I have tried completely deleting the config file, and instead of a config not found message, I still get this same error. I'm hence unable to use this action or debug why this is happening, as the error message does not change.

I have even attempted to keep a file with the default config name ane removed the with/confiig-name property from my workflows/release-draft.yml, but the problem remains the same.

**Comment by casz** [comment]
Looking at this, I assume your config is not on master branch.

**Comment by tayyab-anwar** [comment]
You're correct, it's not. Nor is the workflow yml. 
I am testing on another branch and intend to merge this into master once the tests are successful.

**Comment by tayyab-anwar** [comment]
Also note that I am not pushing to the master branch, I'm pushing the custom branch (DEV-XXXX) and have it set in the release_draft.yml to only work on that branch.
Is the action only set up to run on he master branch?

**Comment by casz** [comment]
The test is push to master and see what happens 😉
This might be an limitation on the current state of probot-config which is "deprecated".
See https://github.com/probot/probot-config/commit/3dc730b53e979f9c5fe85cb296e0075ea03fa07e

**Comment by casz** [comment]
hopefully #399 should provide context loading of config files.

**Comment by tayyab-anwar** [comment]
I can't push to master until I've verified it in my test branch. :(
Hoping your pull request will fix this issue, otherwise I'll try testing on master.

**Comment by casz** [comment]
You don't have to wait.

You can just point to my repo in your workflow:
```yml
uses: casz/release-drafter@fix/config
```

**Comment by tayyab-anwar** [comment]
No luck!

**Comment by casz** [comment]
@tayyab-anwar as suspected the config is loaded from the default branch context.

**Comment by tayyab-anwar** [comment]
After placing the configs into master, it's working as expected.

**Comment by msashkin** [comment]
@casz any chance that the config will be loaded not only from the default branch context?
I'm having the similar issue. I can place my configs in master anyway, but it would be good to test the config first in a separate branch together with gh-action .yml

**Comment by casz** [comment]
This is a limitation inside probot however I say this is properly intended behavior so that somebody cannot introduce something from a pull requests or from a branch.

**Comment by casz** [comment]
@msashkin merge in the release-drafter config into master branch first than do the follow up workflow and everything should be fine

**Comment by msashkin** [comment]
@casz yep, I understand that two merges are required in that situation. Ok, thanks for your help!

**Comment by xenoterracide** [comment]
so it will only work on master? it can't work on develop?

**Comment by jetersen** [comment]
@xenoterracide the release-drafter.yml config has to be on master branch.

You can set up release-drafter to run on multiple branches but the config still needs to be on the default branch to take affect.

**Comment by xenoterracide** [comment]
our default branch is `develop` 'cause some people like gitflow

**Comment by lucagiove** [comment]
> @xenoterracide the release-drafter.yml config has to be on master branch.
> 
> You can set up release-drafter to run on multiple branches but the config still needs to be on the default branch to take effect.

I think this should be remarked in the README documentation because it's a common pitfall

**Comment by peter-dolkens** [comment]
Would be good to clear up if it needs to be on the default branch, or on `master`.

**Comment by mrchief** [comment]
I'm using v5 and it still can't find the config, even if it's in the default branch.

**Comment by iceicys** [comment]
I'm getting the same error below, our master branch was renamed to [develop] due to 

So how do I get this to work with a default branch that is named [develop] and not [master]?

```
Warning: Invalid config file
{
  name: 'ValidationError',
  id: '919609652',
  isJoi: true,
  details: [
    {
      message: '"template" is required',
      path: [ 'template' ],
      type: 'any.required',
      context: { key: 'template', label: 'template' }
    }
```

**Comment by peter-dolkens** [comment]
@mrchief @iceicys  what is the full path to your config file

**Comment by mrchief** [comment]
> @mrchief @iceicys what is the full path to your config file

Same as in the OP: `.github/...`
