### ISSUE TITLE
Multiple labels not grouping under one heading

### ISSUE THREAD

**Issue by tayyab-anwar** [release-drafter/release-drafter#403]
Expected behavior: If there are multiple labels under one grouping, they are expected to be grouped under that heading.
Actual behavior: The heading is being repeated for each label under that title/heading.

Screenshots:
Config file:
![Screen Shot 2020-01-29 at 1 40 53 PM](https://user-images.githubusercontent.com/58931172/73340667-fa4e7a80-429c-11ea-90a5-7833d0d8b0cc.png)

Result:
<img width="812" alt="Screen Shot 2020-01-29 at 1 31 40 PM" src="https://user-images.githubusercontent.com/58931172/73340570-cffcbd00-429c-11ea-98df-2c0be7b1f212.png">

The above have labels bug, bugfix, and sentry respectively.

**Comment by casz** [comment]
This happens because you marked the pull requests with each two or more labels in that category.

Yes it's a bug but I suspect you could remove sentry from the category and you'll be fine.

**Comment by ssbarnea** [comment]
That is a very annoying but and most projects cannot avoid it because there is real need to have multiple labels under the same grouping and no way to make them exclusive.

**Comment by casz** [comment]
feel free to submit a fix 🤔

**Comment by casz** [comment]
I'll see if I can hunt down the bug 😓

**Comment by tayyab-anwar** [comment]
> This happens because you marked the pull requests with each two or more labels in that category.
> 
> Yes it's a bug but I suspect you could remove sentry from the category and you'll be fine.

I tested with multiple scenarios. In the screenshot I have posted, no PR had more than one label.

**Comment by casz** [comment]
I have a working PR your welcome to test very soon :)

**Comment by casz** [comment]
@tayyab-anwar feel free to point your action to my branch: casz/release-drafter@fix/duplicateCategory

**Comment by TimonVS** [comment]
Thanks to @casz this has been fixed and released in [`v5.7.0`](https://github.com/release-drafter/release-drafter/releases/tag/v5.7.0)!
