### ISSUE TITLE
Question: How to disable the App once the Action is installed

### ISSUE THREAD

**Issue by teledyn** [release-drafter/release-drafter#406]
Once I have added the workflow configuration file, do I need to do anything on the github side to disable the previously installed App and enable the Action version?  Just uninstall from the Organization Repository access?

**Comment by casz** [comment]
As simple as removing application access to the repo or the whole organization.

**Comment by teledyn** [comment]
ok thanks, just wanted to be sure that's all.  Seems to be doing it's stuff :)
