### ISSUE TITLE
Question: version number not up to date?

### ISSUE THREAD

**Issue by jonbrohauge** [release-drafter/release-drafter#432]
Seeing the current latest release is 5.6.1, but in packages.json the version is still 5.3.1.

Any sane reason for this?

**Comment by casz** [comment]
we are not pushing anything to npm so 🤷‍♂

**Comment by jonbrohauge** [comment]
@casz ahh cool... Thx for info.
Now on to figure out how to have Github Actions work on Github Enterprise..
