### ISSUE TITLE
Output body from the created release

### ISSUE THREAD

**Issue by sergioflores-j** [release-drafter/release-drafter#461]
Hey guys, I'm enjoying using the Github Action! 
Thanks for the amazing job you're doing, it is a very helpful tool!

I want to know if there's the possibility to add the body that was created on the draft to the Github Action Output. 

It would be nice to have this because I want to have a notification of the release that is being created at "Rocket.Chat" (an open-source Slack) that my company uses to team's communication.

Let me know if there's something I can do to help!

**Comment by Jetersen** [comment]
Should be fairly simple, a PR would be welcomed.

**Comment by jetersen** [comment]
done in #462
