### ISSUE TITLE
The release notes aren't generated

### ISSUE THREAD

**Issue by raisiqueira** [release-drafter/release-drafter#468]
Hi!, i configured the actions on my repo, but when i merge any branch into master returned this message on actions: `Ignoring push. master is not one of: development`.

**Comment by sergioflores-j** [comment]
You have to configure the branches that you want release-drafter to "watch" on the config file, otherwise it'll use the repo's default.

Add something like this into your release-drafter.yml:
```
branches: [master]
```

**Comment by jetersen** [comment]
Simple configuration change
