### ISSUE TITLE
Add config option for `include-labels`

### ISSUE THREAD

**Issue by kreyusb** [release-drafter/release-drafter#499]
There is currently a configuration option to specify labels to exclude.  However for certain repositories (mono-repos come to mind) it would be helpful to have the opposite - to have a configuration option so that the release ONLY includes PRs with the specified labels.

This option would be added to the `release-drafter.yml` and would look something like the following:

```
include-labels:
  - 'application_foo'
```

In this particular example only PR's that have the `application_foo` label would be included in the drafted release.

One point of conversation would be to think about what would happen if the user had both `include-labels` and `exclude-labels` in the configuration.  I believe that `exclude-labels` should take precedence.  That is - if a PR has a label that is in the `include-labels` list as well as a label that is in the `exclude-labels` list the PR should be excluded.  If the user has the same exact label in both lists the configuration should be invalidated.

**Comment by jetersen** [comment]
not sure I can understand the need for include?
Create a single exclude label and add that to your pull-request template and than you can exclude all until your decided on what to include.

**Comment by kreyusb** [comment]
The purpose of the `include-labels` functionality would be primarily to support mono-repo scenarios.  In these cases you will typically have multiple release workflows with multiple `release-drafter` configurations.

Lets say I have a repo with 2 applications I am independently versioning - `Foo` and `Bar`.  Both the applications have some common pieces, but also some completely separate pieces.  If common  code is changed I want to version both applications.  If code specific to just `Foo` changes I only want to version `Foo`.

With `exclude-labels` this cannot be reasonably done.  Suppose I make a change to common code - that results in a PR with both labels `label_foo` and `label_bar`.  If the Foo release-drafter configuration is excluding `label_bar` the PRs modifying common code would be completely excluded from the drafted release.  

If I go with a `label_common_code` the same problem occurs in situations where a PR modified both common code and project `Bar`.  The PR would have both `label_common_code` and `label_bar`.  In this case when it is merged we *should* draft a release for Foo due to the common changes, but if we are excluding items labeled for project Bar this change would not be listed.


Hopefully that helps make my use case more clear?

**Comment by mboudraa** [comment]
I have the need for it. 
There is a lot of chore in my repo and I use this action to generate public facing release notes. 
I'd love to include only Pull Requests labeled `bugfix` or `feature`.
