### ISSUE TITLE
Release-drafter duplicates sections in release notes when using multiple labels

### ISSUE THREAD

**Issue by iphydf** [release-drafter/release-drafter#509]
See e.g.: https://github.com/TokTok/c-toxcore/releases/tag/untagged-a17c289029ac49e0922c

For posterity, here is what release-drafter produced:
```
## Release Notes

- typo: `NAC_LIBS` -> `NACL_LIBS`. @iphydf (#1489)
- cleanup: Stop hard-coding packet IDs in tests. @iphydf (#1496)
- cleanup: Add a check that we don't have any unused functions. @iphydf (#1463)
- cleanup: Include `<string.h>` for `explicit_bzero`. @iphydf (#1462)

## 🚀 Features

- Add logging to TCP and onion client. @iphydf (#1493)

## 🐛 Bug Fixes

- fix: Fix a bug in savedata loading when malloc fails. @iphydf (#1467)
- fix: Fix errors on error paths found by oomer. @iphydf (#1464)

## 🧰 Maintenance

- chore: Add a script to run Travis CI locally. @iphydf (#1473)
- chore: Enable cimple tests by default but allow disabling them. @iphydf (#1436)

## 🧰 Maintenance

- refactor: Limit scope of loop iterators. @iphydf (#1498)
```

It created 2 "Maintenance" sections, one per label. I would have expected all labels to be put into the same section if they appear in the same category. This is the category in question: https://github.com/TokTok/.github/blob/0f96f18848b2fb45fc397135f3ba50466a9199f6/.github/release-drafter.yml#L23-L29.

**Comment by iphydf** [comment]
Another example: https://github.com/TokTok/experimental/releases/tag/untagged-2e0d0c8df1a3f96c60b6

I did get the replacer to work, so #510 seems to be misconfiguration (need `/g` on the regex). Still, the categories are duplicated.

**Comment by jetersen** [comment]
This is fixed on the GitHub action, I have yet to get access to updating the GitHub app.

https://github.com/release-drafter/release-drafter/pull/412

**Comment by jetersen** [comment]
Fixed on both GitHub action and Github app
