### ISSUE TITLE
Replacers seem to not work reliably

### ISSUE THREAD

**Issue by iphydf** [release-drafter/release-drafter#510]
I'm not sure whether this is misconfiguration on my end, but the config [here](https://github.com/TokTok/.github/blob/0f96f18848b2fb45fc397135f3ba50466a9199f6/.github/release-drafter.yml#L2-L4) is supposed to remove all "feat", "chore", etc. tags from the beginning of a release notes item. Instead, release-drafter only removed it from a single item:

```
## Release Notes

- typo: `NAC_LIBS` -> `NACL_LIBS`. @iphydf (#1489)
- cleanup: Stop hard-coding packet IDs in tests. @iphydf (#1496)
- cleanup: Add a check that we don't have any unused functions. @iphydf (#1463)
- cleanup: Include `<string.h>` for `explicit_bzero`. @iphydf (#1462)

## 🚀 Features

- Add logging to TCP and onion client. @iphydf (#1493) <----- this one

## 🐛 Bug Fixes

- fix: Fix a bug in savedata loading when malloc fails. @iphydf (#1467)
- fix: Fix errors on error paths found by oomer. @iphydf (#1464)

## 🧰 Maintenance

- chore: Add a script to run Travis CI locally. @iphydf (#1473)
- chore: Enable cimple tests by default but allow disabling them. @iphydf (#1436)

## 🧰 Maintenance

- refactor: Limit scope of loop iterators. @iphydf (#1498)
```

**Comment by jetersen** [comment]
test shows it is working 😓

I suspect you need to properly escape your backslashes:
```yaml
replacers:
  - search: "/(feat|fix|docs|chore|cleanup|style|refactor|perf|test)(\\(\\w+\\))?: /g"
    replace: ""
```

VScode was warning me about "unknown escape sequence" until I escaped the backslashes.

**Comment by jetersen** [comment]
All fully explained here: http://blogs.perl.org/users/tinita/2018/03/strings-in-yaml---to-quote-or-not-to-quote.html

**Comment by iphydf** [comment]
Thanks, that did it.
