### ISSUE TITLE
Draft based on branch release/v*

### ISSUE THREAD

**Issue by MichelDiz** [release-drafter/release-drafter#515]
I was trying to configure the release-drafter to work with branches. But it doesn't seem to work or I did something wrong. Does it work only with master?

I would like the release-drafter to be executed only e.g.
```
  push:
    branches:
      - 'release/v*' 
```
This happens because the release is done via TeamCity. From there the build happens and etc.

Is it possible?

Cheers.

**Comment by MichelDiz** [comment]
I have tried

added this to the release model
```
branches:
    - 'release/v*'
```
and this to the workflow
```
name: Release Drafter
on:
  push:
    branches:
      - 'release/v*' 
```

It doesn't work with `/v*`
```
17:20:15.533Z  INFO probot: MichelDiz/testActions: Ignoring push. release/v20.1.4 is not one of: release/v*
```

**Comment by jetersen** [comment]
release drafter does not support wildcard.

**Comment by MichelDiz** [comment]
This repo uses https://github.com/actions/create-release
But I think I found a way to do it. I gonna have to add two extra steps.
1 - To install python
2 - To use yaml_cli and edit the version accordingly on the fly.

But support something like https://github.com/isaacs/minimatch that I found https://github.com/actions/labeler using. Would be nice.

**Comment by jetersen** [comment]
You could contribute to release drafter, adding support for wildcards on branches.

**Comment by MichelDiz** [comment]
That could be one, but it would take more time. I gonna study both the minimatch and how this release-drafter works under the hood. But as I don't have time not even for myself. It will be in the long run.

BTW, it is a wonderful tool. Its sad you guys gonna deprecated it.

Cheers.

**Comment by jetersen** [comment]
No depreciation is planned 😬

**Comment by MichelDiz** [comment]
Nice, so I gonna work on it.
There is someplace where I can get tips about the design of the project, best practices, and so on?

Also, I noticed that even If I checkout (forcing it**) the release-drafter seems to ignore it and use the only master as its reference (maybe it is cuz docker?). e.g: If I do a change in v20.1.4 and that thing doesn't exist in master. It won't work and the process will fail.

```
      - name: Checkout to release
        uses: actions/checkout@v2
        with:
          ref: 'release/v20.1.4'
          clean: false
```

> I just wanna a guide where to look. And solve it.

>Everything else works, the only thing I disabled for testing was isTriggerableBranch

The real example I am doing is.
I decided instead of using third party binaries(yaml_cli), to "template it" using a bash script. And on the fly, it will create the final template with the information I need already contextualized.

However, it does not work. For release-drafter will read master and not v20.1.4. Which is where the template was just created. I wanna make release-drafter to checkout to another branch.

Cheers.

**Comment by jetersen** [comment]
The config is always read from default branch context.

**Comment by MichelDiz** [comment]
Okay, sorry the too many comments.

I have added some "console.logs" to understand the flow. I'm able to see the file there. But inside the release-drafter code, "master" is defined as default hardcoded. I have hardcoded the branch myself in the code (and everywhere i could), but no matter what. It always goes back to "master".

Cheers.

**Comment by jetersen** [comment]
#546 would solve most of your trouble regards when GitHub action can trigger release drafter by allowing GitHub action to always trigger!

Regarding multiple configs you could use `config-name` and have multiple configs located on master branch 😓
