### ISSUE TITLE
Published releases doesn't seem to work?

### ISSUE THREAD

**Issue by arminc** [release-drafter/release-drafter#542]
I am testing the https://github.com/release-drafter/release-drafter/pull/424#issuecomment-598830640 because I want to achieve the following: https://github.com/goreleaser/goreleaser-action/issues/207

When using the 5.9.0 release I get the following "##[warning]Unexpected input 'publish', valid inputs are ['entryPoint', 'args']"  when using the example in the PR. I also tried it with ENV but it doesn't work either.

Goal: Use release drafter to draft a release with all the PR's then when the goreleaser releases the code it uses the notes from the draft or converts the draft to original release. But what happens is that the draft stays and goreleaser creates a release next to it, while they both have the same version name. I might be missing something here why it doesn't do what I expected :)

**Comment by jetersen** [comment]
Could you provide your release drafter config?

**Comment by jetersen** [comment]
Seems more your issue is related to #359 
https://github.com/arminc/k8s-platform-lcm/runs/725454978?check_suite_focus=true#step:8:7

**Comment by arminc** [comment]
So if I understand correctly it only works when on master not when setting a tag?

**Comment by jetersen** [comment]
at the moment, yes.

https://github.com/release-drafter/release-drafter#configuration-options
You can configure `branches` section. But it is not very flexible as it does not support wildcards.

**Comment by arminc** [comment]
What I do is, create bunch of PR's and merge them. In the meantime the draft is created so me and others can see what is coming. Then I create a tag which makes a release and then I would like to use the notes in the draft. Before when using travis-ci the draft became the release, not sure how that works but it is that happend. Now that I switched to goreleaser it seems it ignores the draft that is why I wanted to use publish functionality from release drafter.
I will need to either manually copy the note or use something else, it seems these two don't work together right now, or I need to adjust my way of working just not sure how.

**Comment by jetersen** [comment]
Consider contributing to release-drafter to achieve your goal? :)
I would welcome the contributions 😍

**Comment by jetersen** [comment]
I'll look into supporting other references :)

**Comment by jetersen** [comment]
The input errors are there because they are not defined on our `action.yml` I can fix that 😓

**Comment by arminc** [comment]
Thank you for the quick response! I might have a look at the how travis ci picks/uses the draft to create the release. It seems release drafter needs to do a release where it makes much more sense to me, to have the goreleaser use a draft if it is there.

**Comment by jetersen** [comment]
Looking at your current actions workflow, you would have to use release drafter before running gorelease as it would expect a release to be there.

**Comment by arminc** [comment]
It might need to be indeed before not after, goreleaser does add binaries to an actual release, according to the documentation (if I am not mistaken).

**Comment by jetersen** [comment]
Holiday tomorrow, I'll see what I can brew up ☕

**Comment by jetersen** [comment]
I think it makes sense to skip the check for `isTriggerableBranch` when running as github actions, `isTriggerableBranch` is only relatable to us when running as `Probot` though it would be nice to have Probot also trigger on releases.

**Comment by arminc** [comment]
This is very fast fix :) thanks for that. Can't wait for it to be merged, nice work!
