### ISSUE TITLE
##[error]Container action is only supported on Linux

### ISSUE THREAD

**Issue by FDiskas** [release-drafter/release-drafter#558]
Multiplatform support?

**Comment by FDiskas** [comment]
Just copy code from https://github.com/ecampidoglio/auto-release-draft

**Comment by FDiskas** [comment]
If action is runned with node12 it can run on all platforms

**Comment by jetersen** [comment]
true, but we are using a docker image and are tricking the docker image to run probot.
As I said it is blocked by #549

**Comment by jetersen** [comment]
Action has been running on node 12 for a long time thanks to #782 and in v5.16.0 we upgraded to node 16.
