### ISSUE TITLE
Unexpected input 'config-name', valid inputs are ['entryPoint', 'args']

### ISSUE THREAD

**Issue by mr-feek** [release-drafter/release-drafter#559]
I followed the instructions and attempted creating a custom config file. I received the following warning: `Unexpected input 'config-name', valid inputs are ['entryPoint', 'args']`

https://github.com/psalm/psalm-plugin-laravel/actions/runs/127464278

**Comment by jetersen** [comment]
Fixed in #543 not yet released.

**Comment by mr-feek** [comment]
oh sorry! I searched issues, but not PRs :) Thanks!
