### ISSUE TITLE
Only works when default branch is called `master`

### ISSUE THREAD

**Issue by chrisbanes** [release-drafter/release-drafter#563]
I'm currently in the process of renaming my default git branches to `main` instead, unfortunately something in release-drafter seems to only works when it is called `master`.

Workflow: [here](https://github.com/chrisbanes/insetter/blob/main/.github/workflows/release-management.yml)

Log:
```
14:30:41.649Z  INFO probot: chrisbanes/insetter: Found 8 releases
14:30:41.651Z  INFO probot: chrisbanes/insetter: Draft release: untagged-XXXXX
14:30:41.651Z  INFO probot: chrisbanes/insetter: Last release: v0.2.2
14:30:41.652Z  INFO probot: chrisbanes/insetter: Fetching all commits for reference refs/heads/main since 2020-04-27T12:15:17Z
14:30:42.635Z  INFO probot: chrisbanes/insetter: Updating existing release
Deprecation: [@octokit/request-error] `error.code` is deprecated, use `error.status`.
    at RequestError.get (/app/node_modules/@octokit/request/node_modules/@octokit/request-error/dist-node/index.js:29:17)
    at Object.Logger.stdSerializers.err (/app/node_modules/bunyan/lib/bunyan.js:1148:19)
    at /app/node_modules/bunyan/lib/bunyan.js:873:50
    at Array.forEach (<anonymous>)
    at Logger._applySerializers (/app/node_modules/bunyan/lib/bunyan.js:865:35)
    at mkRecord (/app/node_modules/bunyan/lib/bunyan.js:978:17)
    at Logger.error (/app/node_modules/bunyan/lib/bunyan.js:1044:19)
    at Application.<anonymous> (/app/node_modules/probot/lib/application.js:163:33)
    at step (/app/node_modules/probot/lib/application.js:44:23)
    at Object.throw (/app/node_modules/probot/lib/application.js:25:53)
    at rejected (/app/node_modules/probot/lib/application.js:17:65)
14:30:43.031Z ERROR event: Validation Failed: {"resource":"Release","code":"invalid","field":"target_commitish"} (id=XXXXXX)
  HttpError: Validation Failed: {"resource":"Release","code":"invalid","field":"target_commitish"}
      at /app/node_modules/@octokit/request/dist-node/index.js:66:23
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by jetersen** [comment]
That's my bad... target_commitish only takes short refs 😭

**Comment by jetersen** [comment]
we are actually not setting `target_commitish` anymore, so by changing your default branch it should work.

**Comment by chrisbanes** [comment]
My default branch is set to `main`, and release-drafter definitely stopped work once I moved to `main`.

I'm happy to try stuff out if it helps.

**Comment by mattbrictson** [comment]
I ran into this as well. Deleting the draft release (and allowing release-drafter to recreate it with the next build) fixed the error for me.

**Comment by JamesMGreene** [comment]
I ran into this as well but I believe this is actually a maintainer mistake rather than a `release-drafter` mistake. The problem is that we should have updated the `target_commitish` value from `master` to `main` on the existing Draft Release before deleting the `master` branch.

**Comment by jetersen** [comment]
Seems reasonable that existing draft can be deleted or manually updating the target_commitish :)

**Comment by marandaneto** [comment]
having the same issue and I've created the file with the new branch already called `main`:

https://github.com/getsentry/sentry-java/blob/main/.github/workflows/release-drafter.yml

I dont see any previous drafts, is there any workaround? :) thanks

**Comment by khos2ow** [comment]
I had similar issue and wanted to point out, for future readers, that @marandaneto's suggestion (deleting the existing draft release off top of old `master`) also worked for me.

**Comment by SebSept** [comment]
I can't resolve this problem.
`Validation Failed: {"resource":"Release","code":"invalid","field":"target_commitish"}`
workflow acts only on 'dev' branch, 'dev' is the default branch. it has the correct yml.

What do you mean by 'deleting the existing draft' ? I can't see a file to remove ...

https://github.com/SebSept/fop_console/pull/16/checks?check_run_id=2318971519

**Comment by jetersen** [comment]
@SebSept delete the draft on the releases tab: https://github.com/SebSept/fop_console/releases

**Comment by SebSept** [comment]
Thanks a lot @jetersen . It works 👍🏼

**Comment by jetersen** [comment]
Deleting older drafts should work in this case.
