### ISSUE TITLE
Version is ignored?

### ISSUE THREAD

**Issue by arminc** [release-drafter/release-drafter#564]
Reading the readme it states: `The version to be associated with the GitHub release that's created or updated. This will override any version calculated by the release-drafter.` Which would mean if I specify version 0.11.0 it should create/update that one, but it isn't doing that it is creating a new one which is 0.12.0. Am I misreading the version option or is something wrong?

https://github.com/arminc/k8s-platform-lcm/blob/0.11.0/.github/workflows/release.yml

**Comment by jetersen** [comment]
You have to use `$INPUT_VERSION`

```yaml
name-template: v$INPUT_VERSION
tag-template: v$INPUT_VERSION
```

**Comment by jetersen** [comment]
See usage: https://github.com/release-drafter/release-drafter/blob/1eb031648ba18ffa376d3e4f2c33a6364a5a4dc2/.github/workflows/release.yml#L41-L56
