### ISSUE TITLE
Beta and alpha metadata

### ISSUE THREAD

**Issue by TAXSET** [release-drafter/release-drafter#585]
Hi, I'm fairly new to creating ci/cd pipelines for my work and I've been quite fascinated by how easy it is to set up for a user. But now I've run into an issue I don't know how to resolve:

My project repository consists out of 2 base branches, that being master and develop. Develop is actively being used to branch feature branches off of it and receives merges from those branches once they are ready. If the develop reaches a point it's ready to be put into a release, a release-x.x.x branch is branched off. This branch is used for QA and minor bug fixes. Once that branch is working it's merged into master which will build the software and publish it.

And here's my issue: **Is there a way I can append metadata to my release tag?** For example, I need to create a multiple **beta releases** before actually releasing the full version. Does this action support that or do I have to do that manually? **Does this action version resolver support bumping beta.1 to beta.2** or alpha.1 to beta.1? If so, how is it done?

Thanks for your help in advance.

**Comment by jeacott1** [comment]
I have much the same query. I'm producing draft releases from PR with the format v{major}.{minor}.{patch}-{PRID}
where the {PRID} qualifier is the id of the current PR - in this way I can guarantee that no PR's will attempt to write/update another PR's associated release drafts. My {major}.{minor}.{patch} are derived from maven coordinates and hence its entirely possible for several PR's to clash with the same versions if only considering these.

unfortunately after some testing it seems like release-drafter only matches an existing release by the major.minor.patch numbers despite me passing in an input version exactly matching the expected release draft version including the  and name.

is there anything that can be done to at least force an exact match right now?

Thanks in advance.

**Comment by Scotchester** [comment]
Would also love to see the ability to increment alpha/beta releases.

**Comment by jetersen** [comment]
should be possible to craft an action with `filter-by-commitish` and `version` input based on output from another action. Potentially you want to have multiple config files as well.

Though I would suggest git flow is not the best approach to releases and CI/CD:

> Gitflow is a legacy Git workflow that was originally a disruptive and novel strategy for managing Git branches.
> Gitflow has fallen in popularity in favor of [trunk-based workflows](https://www.atlassian.com/continuous-delivery/continuous-integration/trunk-based-development), which are now considered best practices for modern continuous software development and [DevOps](https://www.atlassian.com/devops/what-is-devops) practices.
> Gitflow also can be challenging to use with [CI/CD](https://www.atlassian.com/continuous-delivery). This post details Gitflow for historical purposes.
> https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow
