### ISSUE TITLE
Fails to create notes if it is repos first releases 

### ISSUE THREAD

**Issue by connorguy** [release-drafter/release-drafter#601]
## Issue
I had a new repo with no releases and was testing. Looks like if there are no previous releases this doesn't actually make a draft release.

## Steps to reproduce
1. Create a new repo with no releases
2. Setup github action for release-drafter
3. merge a pr 
4. confirm no draft made, but action successfully ran

**Comment by tk8817** [comment]
Looks like this is the same issue as #626

**Comment by matewilk** [comment]
I'd also love to hear if there is a solution for that, I just introduced `release-drafter` in my repo, I added an empty `CHANGELOG.md` file (so I assume `release-drafter` fills it in automatically?)

And my job fails silently with this:

>  Run release-drafter/release-drafter@v53s
>     GITHUB_TOKEN: ***
> Run release-drafter/release-drafter@v5
>   with:
>     config-name: release-drafter.yml
>   env:
>     GITHUB_TOKEN: ***
> /usr/bin/docker run --name b3ac6fc8f3b317fda404fb4bef61877204c90_5d9ff5 --label 3b3ac6 --workdir /github/workspace --rm -e GITHUB_TOKEN -e INPUT_CONFIG-NAME -e INPUT_NAME -e INPUT_TAG -e INPUT_VERSION -e INPUT_PUBLISH -e INPUT_PRERELEASE -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/newrelic-social-listening-service-nodejs/newrelic-social-listening-service-nodejs":"/github/workspace" 3b3ac6:fc8f3b317fda404fb4bef61877204c90
> 15:40:09.997Z  INFO probot: newrelic-experimental/newrelic-social-listening-service-nodejs: Found 1 releases
> 15:40:09.998Z  INFO probot: newrelic-experimental/newrelic-social-listening-service-nodejs: Draft release: 
> 15:40:09.999Z  INFO probot: newrelic-experimental/newrelic-social-listening-service-nodejs: No last release found
> 15:40:10.000Z  INFO probot: newrelic-experimental/newrelic-social-listening-service-nodejs: Fetching all commits for reference refs/heads/main
> 15:40:11.439Z  INFO probot: newrelic-experimental/newrelic-social-listening-service-nodejs: Updating existing release

**Comment by s-canchi** [comment]
I ran into the same problem but if you click on the `Create a new release` on the GitHub repo main page and then subsequently click on Releases, you will find the draft of the release notes generated by this GitHub Action.

**Comment by jetersen** [comment]
Newer version should definitely create a draft though there is a issue with what the version is resolved to.
