### ISSUE TITLE
Feature Request: Use labels off of linked issue(s)

### ISSUE THREAD

**Issue by zackkrida** [release-drafter/release-drafter#602]
Our team largely labels issues, but not the PR providing the fix. It'd be awesome if `release-drafter` could sort via the labels off of linked issues, rather than the PR itself.

**Comment by jetersen** [comment]
There is no efficient API for doing that.

**Comment by zackkrida** [comment]
Bummer, I'll close this then 👍 it's not hard to label our PRs too. Awesome lib, thank you for this!

**Comment by jetersen** [comment]
As you can see here: https://github.community/t/get-all-issues-linked-to-a-pull-request/14653/6
You have to get a timeline for each PR: pulling out way more data than we are already doing.
And even than you might miss them when it is linked in the description :(

**Comment by zackkrida** [comment]
Wow, that's quite unreliable, reading a timeline of events and parsing out linked issues. I totally get it. Thanks!
