### ISSUE TITLE
Long build times

### ISSUE THREAD

**Issue by mrchief** [release-drafter/release-drafter#604]
Because this action is published as a Docker action, it takes more than a minute to build the image:

![image](https://user-images.githubusercontent.com/781818/88467127-9c909900-cea1-11ea-93f3-fbdb99cf16ab.png)

On private, highly active repos, this causes high usage of build minutes which eats into the quota.

Github supports Node JS actions - if this was published simply as Node JS actions, the docker build times can be cut down drastically.

**Comment by jetersen** [comment]
#549

**Comment by jetersen** [comment]
Action no longer uses docker
