### ISSUE TITLE
Escape titles

### ISSUE THREAD

**Issue by Happypig375** [release-drafter/release-drafter#609]
E.g. https://github.com/Happypig375/github-actions-for-packages/pull/5's title is `</details>`, but when but into release changes it gets interpreted as HTML and becomes hidden. Release Drafter should escape `$TITLE` by default.

**Comment by jetersen** [comment]
You could change your PR title `</details>`

**Comment by jetersen** [comment]
Common practice, thanks to https://github.com/sindresorhus/refined-github

**Comment by Happypig375** [comment]
Yes in this case (it's me testing), but people open PRs without thinking about Release Drafter. They can include \`s and \-s which mess with the generated markdown

**Comment by jetersen** [comment]
Feel free to send a PR :)

**Comment by Happypig375** [comment]
Where to modify?

**Comment by jetersen** [comment]
Good question, not even sure escaping is desired in the first place.

**Comment by Happypig375** [comment]
At least this is a problem with the default provided template.

**Comment by jetersen** [comment]
Agree to disagree :) I do not see the problem as the maintainer of a repo your free to edit a PR title causing trouble.

**Comment by Happypig375** [comment]
`\<`, `\-`, `\+`, `\*`, `\_`, `\>`
\<
\>
\-
\+
\*
\_

**Comment by Happypig375** [comment]
replacers also replace the PR body which is already markdown.

**Comment by Happypig375** [comment]
The title is not markdown but is interpolated into markdown directly without escaping.

**Comment by jetersen** [comment]
Knowing that title's becomes markdown is part of the fun with release-drafter.

backticks should not be escaped.
I seen it be used several times

See usage here: 
https://github.com/jenkinsci/configuration-as-code-plugin/releases/tag/configuration-as-code-1.41
https://github.com/jenkinsci/configuration-as-code-plugin/pull/1379
https://github.com/jenkinsci/configuration-as-code-plugin/releases/tag/configuration-as-code-1.34
https://github.com/jenkinsci/configuration-as-code-plugin/pull/1203

Brackets should not be escaped as 
`&#x3E;=` is not equal to `>=` which on my browser using font ligatures shows up as a single character.

**Comment by Happypig375** [comment]
What about
https://github.com/asc-community/AngouriMath/issues/55
(x^2+2x*y+y^2)/(x+y) Simplify-> x+y but (x^2+2x*y+y^2)/(x^2-y^2) Simplify-> (x^2+2x*y+y^2)/(x-y)/(x+y)

**Comment by Happypig375** [comment]
![image](https://user-images.githubusercontent.com/19922066/89059266-7718f900-d393-11ea-8297-a670d3e35446.png)

**Comment by Happypig375** [comment]
I am talking about using backslashes, not using HTML escapes.

**Comment by jetersen** [comment]
So you can accept markdown escaping for your titles but not accept being able to use markdown freely in your titles.

**Comment by Happypig375** [comment]
So why is displaying titles like how GitHub display titles a problem?

**Comment by Happypig375** [comment]
GitHub titles are not markdown and you cannot treat it like so.

**Comment by jetersen** [comment]
I'll happily continue to treat it like markdown in my release notes and that's the difference PR titles become your release notes ie. markdown.

**Comment by jetersen** [comment]
Again feel free to submit a PR that shows a good use case perhaps with the ability to turn it off and on than maybe.

**Comment by Happypig375** [comment]
And any *stars in titles will become italics,
 propagating across* lines.

**Comment by Happypig375** [comment]
>So why is displaying titles like how GitHub display titles a problem?

Question not answered :)

**Comment by jetersen** [comment]
Because I seen usage of the opposite.

**Comment by Happypig375** [comment]
And I have seen https://github.com/ForNeVeR/wpf-math/pull/270/files

**Comment by jetersen** [comment]
Not sure what that has to do with how people use release-drafter and how they write their PR titles.

**Comment by Happypig375** [comment]
That is an example of how people open issues and PR with titles that don't consider markdown, and Release Drafter should take into account of such cases.

**Comment by jetersen** [comment]
You as a maintainer are able to modify the PR title and let release drafter run again.

**Comment by Happypig375** [comment]
And the title as displayed by GitHub will contain extra backslashes that clutter reading?

**Comment by jetersen** [comment]
Why use backslahes when you can use backticks to show off coding example?

**Comment by Happypig375** [comment]
Because backticks cannot be escaped? Show me how you can contain a backtick inside a code block.

**Comment by Happypig375** [comment]
Or triple backticks inside a multiline code block.

**Comment by jetersen** [comment]
Again currently several people uses backticks when using release-drafter. What your asking for is a breaking change.

https://github.com/testcontainers/testcontainers-java/pull/2932
https://github.com/testcontainers/testcontainers-java/pull/2834
https://github.com/testcontainers/testcontainers-java/pull/2987

There are many more over at https://github.com/testcontainers/testcontainers-java/releases

**Comment by Happypig375** [comment]
Backticks can be used to imitate a code block, or be interpreted as a JavaScript templated string. You can't just decide that all backticks mean code blocks.

>breaking change

Extra flag parameter is OK by me, but you should give the green light first.

**Comment by Happypig375** [comment]
Also see https://github.com/testcontainers/testcontainers-java/releases/tag/1.10.0 where the `nullable` organisation is mentioned.

**Comment by Happypig375** [comment]
Om https://github.com/testcontainers/testcontainers-java/releases, they add backticks manually so what you say isn't really true.

**Comment by jetersen** [comment]
what? I gave you 3 PRs with backticks in them so sure. Whatever.

**Comment by jetersen** [comment]
fyi `\@nullable` is still a mention for `@nullable `

**Comment by Happypig375** [comment]
The 3 PRs you gave are from the core maintainer(s), so they obviously know about Release Drafter and use this as a way as a shortcut. There are PRs without backticks but their titles are formatted as code blocks in releases.

**Comment by Happypig375** [comment]
I gave an example of how outside contributors don't care about markdown formatting in titles.

**Comment by jetersen** [comment]
Feel free to create a PR that considers all corner cases that you see and deem fixable/desireable.
