### ISSUE TITLE
On workflows with both push and pull_request triggers, release-drafter on pull_request returns empty release id

### ISSUE THREAD

**Issue by Happypig375** [release-drafter/release-drafter#612]
https://github.com/verybadcat/CSharpMath/pull/151/checks?check_run_id=935607417

**Comment by Happypig375** [comment]
Does release-drafter only work on `push`?: https://github.com/release-drafter/release-drafter/blob/f25ed7787b93a0c8d3bf978ce730b5480a3c03b0/index.js#L15

**Comment by KrasserTommy** [comment]
I have the same problem. Is it possible to use Release Drafter with pull_request?

**Comment by jetersen** [comment]
This is one of the reason it would be useful to split codebase #549

**Comment by Klausmd5** [comment]
Does also not work, if you trigger it manualy via `workflow_dispatch:` and puts empty tag_name . And it won 't create a release.

**Comment by jetersen** [comment]
You cannot, not without splitting the codebase.

**Comment by jeacott1** [comment]
this action is so frustrating. it insists its config lives in the default branch, so its impossible to test config without merging to master, and now I find it cant be triggered on pull_request (or anything but push).
in my case I want my PR to generate my release + artifacts + notes, and upon merging my PR I don't want anything at all to happen to my release.
without being able to trigger this and have it actually work on pull_request (or whatever event I care to be using), its impossible to properly coordinate my release steps (thanks github actions). 

it would be terrific if there was support for pull_request at least.

**Comment by jetersen** [comment]
This should be resolved in newer versions after #632 and and #546
