### ISSUE TITLE
Incorrect major version bumping

### ISSUE THREAD

**Issue by tianhaoz95** [release-drafter/release-drafter#635]
![Screenshot from 2020-08-31 23-28-19](https://user-images.githubusercontent.com/16887772/91809539-ad8ba300-ebe1-11ea-9ab0-7dd01682731b.png)

In this example, https://github.com/tianhaoz95/approveman/releases, somehow the version jumped from 1.0.0 to 96.1.0 where 4 chore and 5 fixes should bump it to 1.0.9 with this config https://github.com/tianhaoz95/approveman/blob/master/.github/release-drafter.yml since they have chore tag like this one https://github.com/tianhaoz95/approveman/pull/46.

Is there something else that has caused it to overwrite the version from the tags?

**Comment by jetersen** [comment]
That's because your tag is not correct: `https://github.com/tianhaoz95/approveman/tree/untagged-96fc81dd751444e9f0a7` `untagged-96fc81dd751444e9f0a7`

**Comment by tianhaoz95** [comment]
Oh that makes sense. Are you familiar with the mechanism how that tag was generated since I don't remember doing a `git tag`?

**Comment by jetersen** [comment]
When you release a draft from releases tab you have to choose a tag if you do not change it. Release drafter will use the untagged commit

**Comment by tianhaoz95** [comment]
That explains everything. I must have somehow ignore the field. Now it's working. Thanks!
