### ISSUE TITLE
Why is my major version so large?

### ISSUE THREAD

**Issue by wjk** [release-drafter/release-drafter#641]
I am working on adopting release-drafter [for my project](https://github.com/wjk/MSIExtractApp). I pushed a tag to test the release build, which failed halfway through. (This happens concurrently with release-drafter.) [The release notes](https://github.com/wjk/MSIExtractApp/releases/tag/untagged-d31267dafcdbfbfe94f7) look good, just as I intend. However, the next release (currently in draft, while I work on fixing the build failures) looks like this:

<img width="967" alt="screenshot of draft release" src="https://user-images.githubusercontent.com/1915951/92483944-68eea180-f1b7-11ea-99a3-139a438d05da.png">

My question is this: Why did the major version number jump to 31267, and how can I get it back down so that the next release is 1.1.2 (and then 1.1.3, 1.2, and so on)? Thanks!

**Comment by jetersen** [comment]
Remember to tag your release properly:

`https://github.com/wjk/MSIExtractApp/releases/tag/untagged-d31267dafcdbfbfe94f7`, `untagged-d31267dafcdbfbfe94f7` is not a `v1.1.1` tag that release-drafter can understand

**Comment by wjk** [comment]
The thing is, release-drafter chose that name, as far as I can tell. I certainly didn't type that long hex string in. If I use a tag that is correctly named, will the problem fix itself? Thanks!

**Comment by wjk** [comment]
Update: I attempted to rename the tag in the draft PR that release-drafter maintains; it did nothing, and in fact reverted itself back to the long “untagged” string.

**Comment by jetersen** [comment]
You need to change the release to use another tag.
Also deleting tags is required to do in both local and remote repo.

**Comment by wjk** [comment]
I deleted the erroneous tag in both my local clone and my github repo. I then manually tagged `v1.1.2` and pushed it; the release still says "31267.0.1". Could you please clarify what I am doing wrong?

**Comment by jetersen** [comment]
Did you delete the bad draft?

**Comment by wjk** [comment]
No, but now there is no draft. I'll try to regenerate it.

**Comment by wjk** [comment]
The draft now says "What's new in MSI Viewer 1.1.3." This problem seems solved. I'll close this issue for now, but if this problem reoccurs, I'll reopen it. Thanks so much!
