### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by mloning** [release-drafter/release-drafter#649]
Hi and thanks for creating this tool! 

Two questions: 

* Is it possible to make the PR links more explicit, so that they are preserved when I copy the draft text to a CHANGELOG.md file? Or is there another intended workflow for that? 
* Is it possible to categories PRs by labels?

**Comment by jetersen** [comment]
You can use `change-template: '- $TITLE @$AUTHOR ($URL)'
See the docs on autolabeler: https://github.com/release-drafter/release-drafter#autolabeler
