### ISSUE TITLE
Group changes by a specific [robot] author?

### ISSUE THREAD

**Issue by gvolpe** [release-drafter/release-drafter#662]
In the Scala community, there is a robot (@scala-steward) that updates dependencies and it generates a high number of PRs. Is it possible to list all the changes by this specific author in a different section? e.g.

## What's changed
- change 1 by @gvolpe
- change 2 by @author2

## Dependency updates
- change 1 by @scala-steward
- change 2 by @scala-steward
- change N by @scala-steward

**Comment by jetersen** [comment]
Using labels it is

**Comment by gvolpe** [comment]
@jetersen thanks for the prompt reply! Okay so that means I do have to use something like this? https://github.com/TimonVS/pr-labeler-action

**Comment by jetersen** [comment]
You could. Why not modify scala-steward to label the PR it generates?

**Comment by gvolpe** [comment]
Not sure what you mean. At the moment, it does not generate any label at all. Is that configurable without using an extra action? Here's an example of a PR from @scala-steward: https://github.com/gvolpe/pfps-shopping-cart/pull/191

**Comment by jetersen** [comment]
so scala-steward does not seem to support doing labels but you can use another bot. Take the use case from scala-steward project.
https://github.com/scala-steward-org/scala-steward/blob/2d76858d861d50fc175abca1ab71e6e62f9a3bc7/.mergify.yml#L1-L9

**Comment by gvolpe** [comment]
It would be great if it could be done without labels but using labels as a workaround is fine. What I had in mind was something like:

```yaml
categories:
  - title: '🚀 Dependency updates'
    author: 'scala-steward'
  - title: '🧰 Changes'
    author: '*' # the rest except scala-steward
```

Mergify has a similar configuration to filter by author: https://github.com/gvolpe/pfps-shopping-cart/blob/master/.mergify.yml

**Comment by jetersen** [comment]
Not going to support authors. The intent is to support labels.

**Comment by gvolpe** [comment]
Oh that's cool, I'm already using Mergify so that could work, thanks!
