### ISSUE TITLE
Create pre-built "release-drafter" docker image

### ISSUE THREAD

**Issue by socheatsok78** [release-drafter/release-drafter#666]
Hi, I really like to use `release-drafter` with my projects, but it been taking quite a bit of time to the workflow to finish.

Wouldn't. be nice if we have a pre-built docker image for `release-drafter` instead of building it at workflow runtime?

![image](https://user-images.githubusercontent.com/4363857/95657355-52cd5b80-0b3e-11eb-992b-e732b239b957.png)

**Comment by socheatsok78** [comment]
Since running `yarn install` would take a while.

**Comment by jetersen** [comment]
again the correct thing is not fixing the docker image. However it is splitting the code base #549

**Comment by socheatsok78** [comment]
> again the correct thing is not fixing the docker image. However it is splitting the code base #549

Yes agree, either splitting the code base or fixing docker image. Both would resolve the issues. 👍

**Comment by socheatsok78** [comment]
Close this so that it doesn't clog up your issues!
