### ISSUE TITLE
Config validation errors, please fix the following issues in release-drafter.yml

### ISSUE THREAD

**Issue by cliu123** [release-drafter/release-drafter#669]
I've had release-drafter.yml file in the "workflows" and another file with the same name and template in .github/ as you can see: https://github.com/cliu123/security/tree/Create_release-drafter. But I still got the following error after pushing code change to branch "Create_release-drafter".

Config validation errors, please fix the following issues in release-drafter.yml:
Error: "template" is required
https://github.com/cliu123/security/runs/1239503094?check_suite_focus=true

**Comment by jetersen** [comment]
Please remove this line.
https://github.com/cliu123/security/blob/9658ffeb9d02e2a84602b0a9e1a1155247f4cead/.github/release-drafter.yml#L2
You do not have a `.github` repo

Proper use for `.github` is like this:
https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/.github/release-drafter.yml
https://github.com/jenkinsci/.github/blob/master/.github/release-drafter.yml

**Comment by jetersen** [comment]
also your default branch does not have the release-drafter.yml file:
https://github.com/cliu123/security/tree/master/.github

**Comment by cliu123** [comment]
> also your default branch does not have the release-drafter.yml file:
> https://github.com/cliu123/security/tree/master/.github

After revising the .github/release-drafter.yml file in the following way and adding release-drafter.yml file in the master branch, the action still failed as you can see in the second link.:
https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/.github/release-drafter.yml
https://github.com/cliu123/security/actions/runs/302598918

Is there anything else that I should change?

**Comment by jetersen** [comment]
the release drafter config needs to be apart of the default branch as I mentioned above.

**Comment by cliu123** [comment]
> the release drafter config needs to be apart of the default branch as I mentioned above.

Is this what you’re referring to?
https://github.com/cliu123/security/blob/master/.github/release-drafter.yml

Please correct me if I’m wrong. Thanks!

**Comment by jetersen** [comment]
You only need to use extends if you plan on using it in multiple repos and not wanting to copy paste the config.

**Comment by cliu123** [comment]
Even after removing _extend from [.github/release-drafter.yml file](https://github.com/cliu123/security/blob/master/.github/release-drafter.yml), the error still happens. 
https://github.com/cliu123/security/runs/1243924026?check_suite_focus=true
Is there anything else I can do to fix it?

**Comment by jetersen** [comment]
You need to configure your release-drafter.yml like how you want it.

Please read the manual.
https://github.com/release-drafter/release-drafter#example

**Comment by cliu123** [comment]
But what the error complains is missing template. Why does it happen even though I have "template" in the .github/release-drafter.yml file?

**Comment by jetersen** [comment]
@cliu123 most of your config is commented out so clearly it won't work
https://github.com/cliu123/security/blob/63645883adb0d75fb159d3ef2a5d9e0901f7c666/.github/release-drafter.yml#L60-L62

**Comment by cliu123** [comment]
@jetersen It works for me. I'm ready to configure the content of the release draft now. Thanks for help!
