### ISSUE TITLE
Dev workflow for github action

### ISSUE THREAD

**Issue by timja** [release-drafter/release-drafter#674]
Hi,

I'm looking at fixing https://github.com/release-drafter/release-drafter/issues/578

Is there a good dev workflow for the github action version?

I was trying running the docker image but seem to just get:

```
Usage: probot-receive [options] [path/to/app.js...]

Options:
  -e, --event <event-name>           Event name
  -p, --payload-path <payload-path>  Path to the event payload
  -t, --token <access-token>         Access token
  -a, --app <id>                     ID of the GitHub App (default: "85234")
  -P, --private-key <file>           Path to certificate of the GitHub App
  -h, --help                         display help for command
```

**Comment by timja** [comment]
I tried `act` but it doesn't work here.

ended up just pushing a branch and pointing the action at my fork.

**Comment by jetersen** [comment]
I'd rather wait for #549 😓

**Comment by jetersen** [comment]
added a dev container, `yarn test` should be sufficient for most cases.
