### ISSUE TITLE
Accept GitHub Marketplace Developer Agreement, thanks.

### ISSUE THREAD

**Issue by jetersen** [release-drafter/release-drafter#679]
Hi @TimonVS @toolmantim 
I do not have the powers to accept the GitHub Marketplace Developer Agreement.

release-drafter must accept the GitHub Marketplace Developer Agreement. Contact an org admin to accept it.

![image](https://user-images.githubusercontent.com/1661688/96500883-d5959b00-124f-11eb-9c01-f26d20f33a99.png)

Would it be possible that I could have the powers or would you prefer to do it?

**Comment by toolmantim** [comment]
All done! Thanks @jetersen

**Comment by jetersen** [comment]
This is an issue again 😓

**Comment by toolmantim** [comment]
Gah! All fixed. Thanks @jetersen!
