### ISSUE TITLE
"No draft release found" when running CD

### ISSUE THREAD

**Issue by wjk** [release-drafter/release-drafter#680]
Please take a look at [this GitHub Actions workflow file](https://github.com/wjk/MSIExtractApp/blob/master/.github/workflows/CD.yml). This file is supposed to run release-drafter both to move the Draft release it maintains to the tag I just pushed, and to obtain the `upload_url` output so I can upload prebuilt artifacts to it later. However, every time I push a tag, the action gives me the following output:

```
Found 5 releases
No draft release found
No last release found
Fetching all commits for reference refs/tags/v1.2.1-rc.1
Creating new release
```

release-drafter then proceeds to ignore the draft release it maintains (which is still updated correctly when I merge a PR; I tested that) and creates a new one with an unset version (containing `$RELEASE_VERSION` verbatim in the text and a meaningless hashed tag), that lists every PR ever merged into the repo since it was created.

What I want to have happen is if I push the tag `v1.2.1`, it moves the untagged Draft release to the `v1.2.1` tag, ensures that only PRs merged between now and when the previous version was published are displayed, then returns the `upload_url` for later use. How can I configure release-drafter to do this? I do not want to publish the release automatically when the action is run, as one final safety check so I can edit anything if I need to before I make it available to the world. Please also be aware of the following caveats:

* I must run release-drafter in a separate job before my build, because I am building a Windows app and release-drafter only runs on a Linux image.
* I cannot split the build job into two parts (and run release-drafter in-between), as then the release assets would be deleted when the first job finishes, making it impossible to upload them in the second job.

I hope I've explained this clearly; it is a very confusing problem for me. If you have any other questions, please feel free to ask. Thanks so much!

**Comment by valentijnscholten** [comment]
I saw the same, but was caused by #681

**Comment by jetersen** [comment]
Hopefully reverting #657 should fix it.

**Comment by wjk** [comment]
Using v5.12.1 of release-drafter fixed the problem; it now works like a charm. Thanks!
