### ISSUE TITLE
Release Drafter picking up an old version from the repository

### ISSUE THREAD

**Issue by yasoobz** [release-drafter/release-drafter#684]
Hi

Issue:

Whenever a PR is being merged into the target branch (dev), the Release Drafter action is creating the draft for an old version.

Currently we are at v1.27.0. So the next version should be v1.27.1.

However, release-drafter is picking up v1.3.66 as the last release, and therefore creating a draft with version v1.3.67. It is also adding all the PRs since that release in the draft (couple of hundred). As you can see in SS attached, the date being shown is 7th Feb 2020.

Wrong version being picked by RD:

<img width="1410" alt="Screenshot 2020-10-21 at 12 20 00 PM" src="https://user-images.githubusercontent.com/27990813/96683384-c02b8880-1397-11eb-9802-73cefe637c89.png">

Our setup:
<img width="983" alt="Screenshot 2020-10-21 at 12 20 22 PM" src="https://user-images.githubusercontent.com/27990813/96683430-cd487780-1397-11eb-8275-6393effb3ece.png">

<img width="980" alt="Screenshot 2020-10-21 at 12 20 38 PM" src="https://user-images.githubusercontent.com/27990813/96683458-d6394900-1397-11eb-9f5f-bb89635f86b4.png">

Please help in pointing me to the possible cause here.

**Comment by mkurz** [comment]
You might be interested in [#656 (comment)](https://github.com/release-drafter/release-drafter/issues/656#issuecomment-806184887) and also [#1061](https://github.com/release-drafter/release-drafter/issues/1061)

**Comment by jetersen** [comment]
Not sure this is relevant anymore and is most likely fixed in newer versions.
