### ISSUE TITLE
Change title level for categories

### ISSUE THREAD

**Issue by ewjoachim** [release-drafter/release-drafter#708]
The lib hard codes that categories must be level 2 markdown heading (`##`)

https://github.com/release-drafter/release-drafter/blob/a3b34cc0818b1f1e9db74884263fdf46607090f2/lib/releases.js#L196

Do you think this could be parametrized ?

**Comment by jetersen** [comment]
was added in #767

**Comment by ewjoachim** [comment]
Yay nice !

**Comment by ewjoachim** [comment]
If you're interested, I'm using this action with https://github.com/ewjoachim/sphinx-github-changelog : this action produces the drafts, and when published, the docs CI will read the HTML version of the release from the GitHub API and insert it in the Changelog part of the built docs. The level of titles was one of the things that made it slightly complicated to be as nice as should be (`#` is the title of the doc and `##` the title of the changelog section, so each changelog release should be `###`)
