### ISSUE TITLE
Creating new release fail uses: release-drafter/release-drafter@v5.12.1

### ISSUE THREAD

**Issue by GitHubWebb** [release-drafter/release-drafter#727]
[please see link](https://github.com/GitHubWebb/frameLibraryWidget/runs/1510583246?check_suite_focus=true)

**Comment by GitHubWebb** [comment]
![Screenshot_20201207_210408](https://user-images.githubusercontent.com/24510234/101354414-19ac3000-38d0-11eb-959b-e4a3a25b7f5a.jpg)

`1
Warning: Unexpected input(s) 'body', 'draft', valid inputs are ['entryPoint', 'args', 'config-name', 'name', 'tag', 'version', 'publish', 'prerelease']
2
Run release-drafter/release-drafter@v5.12.1
16
/usr/bin/docker run --name fd7c34b05a98a8013e6ba71e1_e474d8 --label 179394 --workdir /github/workspace --rm -e GITHUB_TOKEN -e INPUT_CONFIG-NAME -e INPUT_BODY -e INPUT_PUBLISH -e INPUT_PRERELEASE -e INPUT_DRAFT -e INPUT_NAME -e INPUT_TAG -e INPUT_VERSION -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/frameLibraryWidget/frameLibraryWidget":"/github/workspace" 179394:9594385fd7c34b05a98a8013e6ba71e1
17
12:21:48.120Z  INFO probot: GitHubWebb/frameLibraryWidget: Found 51 releases
18
12:21:48.122Z  INFO probot: GitHubWebb/frameLibraryWidget: No draft release found
19
12:21:48.122Z  INFO probot: GitHubWebb/frameLibraryWidget: Last release: release-v2.0.25
20
12:21:48.123Z  INFO probot: GitHubWebb/frameLibraryWidget: Fetching all commits for reference refs/heads/master since 2020-12-07T11:56:24Z
21
12:21:48.483Z  INFO probot: GitHubWebb/frameLibraryWidget: Creating new release
22
Deprecation: [@octokit/request-error] `error.code` is deprecated, use `error.status`.
23
12:21:49.502Z ERROR event: Validation Failed: {"resource":"Release","code":"already_exists","field":"tag_name"} (id=1184f28b-531b-4ad8-8e62-1441f4f60191)
24
    at RequestError.get (/app/node_modules/@octokit/request/node_modules/@octokit/request-error/dist-node/index.js:29:17)
25
  HttpError: Validation Failed: {"resource":"Release","code":"already_exists","field":"tag_name"}
26
    at Object.Logger.stdSerializers.err (/app/node_modules/bunyan/lib/bunyan.js:1148:19)
27
      at /app/node_modules/@octokit/request/dist-node/index.js:66:23
28
    at /app/node_modules/bunyan/lib/bunyan.js:873:50
29
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
30
    at Array.forEach (<anonymous>)
31
  --
32
    at Logger._applySerializers (/app/node_modules/bunyan/lib/bunyan.js:865:35)
33
  event: {
34
    at mkRecord (/app/node_modules/bunyan/lib/bunyan.js:978:17)
35
    "event": "push",
36
    at Logger.error (/app/node_modules/bunyan/lib/bunyan.js:1044:19)
37
    "id": "1184f28b-531b-4ad8-8e62-1441f4f60191",
38
    at Application.<anonymous> (/app/node_modules/probot/lib/application.js:163:33)
39
    "repository": "GitHubWebb/frameLibraryWidget"
40
    at step (/app/node_modules/probot/lib/application.js:44:23)
41
  }
42
    at Object.throw (/app/node_modules/probot/lib/application.js:25:53)
43
    at rejected (/app/node_modules/probot/lib/application.js:17:65)
`

**Comment by jetersen** [comment]
the error should be apparent. Both body and draft are invalid input fields to the action.
Those are meant for the config file.

**Comment by GitHubWebb** [comment]
> 该错误应该很明显。正文和草稿都是该操作的无效输入字段。
> 这些是用于配置文件的。

However, I did not do other operations, the code comes from the template, how should I deal with it now

**Comment by GitHubWebb** [comment]
> the error should be apparent. Both body and draft are invalid input fields to the action.
> Those are meant for the config file.

However, I did not do other operations, the code comes from the template, how should I deal with it now

**Comment by jetersen** [comment]
Remove the unknown parameters from the action?

**Comment by GitHubWebb** [comment]
> Remove the unknown parameters from the action?

I think it may be related to my call, the error message that occurred shows "No draft release found",I have two branches that are executing the ation of different branches. It is very likely that there is a problem in generating or reading the tag name. What should I do? It is necessary to run multiple actions at the same time. Can I add the tag name, for example: master-v-1.0.0/dev-v-1.0.0

**Comment by jetersen** [comment]
We are past this release
