### ISSUE TITLE
Release Drafter Action doest't work

### ISSUE THREAD

**Issue by pvsaintpe** [release-drafter/release-drafter#737]
Hi!

When I use your action, I receive this error:
```
ValidationError: child "template" fails because ["template" is required]
```

This is my build:
https://github.com/umbrellio/laravel-pg-extensions/runs/1602970010?check_suite_focus=true

![image](https://user-images.githubusercontent.com/16900171/103045373-4aa98780-4595-11eb-9347-b4ce945fcdac.png)

I did everything according to your example from GitHub.
Please point out my mistakes in the config.

Here my config:
https://github.com/umbrellio/laravel-pg-extensions/blob/master/.github/release_drafter.yml

Thank you in advance.

**Comment by jetersen** [comment]
https://github.com/umbrellio/laravel-pg-extensions/blob/e4a5bcbfb985cd04ea75eaece85d1c85b2666b91/.github/workflows/auto_release.yml#L14

Should be 
```
          config-name: "release_drafter.yml"
```

**Comment by pvsaintpe** [comment]
@jetersen Thanks.
