### ISSUE TITLE
support out of band patch release with git flow where all releases are from master

### ISSUE THREAD

**Issue by valentijnscholten** [release-drafter/release-drafter#756]
Hi,

We're using release drafter on a project that uses `semver` and has the following release schedule based on [git flow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow)
- monthly: merge dev into master and create a (regular) release
- ad hoc: merge hotfix into master and create a (hotfix) release

![image](https://user-images.githubusercontent.com/4426050/104452788-c64e9100-55a3-11eb-812c-40d32b82c132.png)

Release drafter is configured to look at both branches to  draft our releases:
- release-drafter.yml on dev looks at dev branch
- release-drafter.yml on master looks at master branch

Currently when you create a hotfix release, release drafter "forgets" (ignores) all PRs merged since the latest (regular) release but before the hotfix release.

i.e.
- Release 1.0.0
- PR100 merged to dev
- PR101 merged to dev
- Hotfix1 merged to master
- Release 1.0.1 from master
- release drafter lists Hotfix1 on release notes for 1.0.1 on master (OK)
- release drafter lists nothing on release  1.1.0 on dev (NOK)

In this scenario we "loose" PR100 and PR101 on the draft release notes. 

Is there anyway to support this scenario? 

One solution could be to allow a parameter with a list of releases to ignore.
A workaround might be to use the `filter-by-commitish` and not release from `master` but from a hotfix branch (an possible from `dev` instead of `master` or a release branch instead of `master` for regular releases).

Any thoughts?

**Comment by jetersen** [comment]
For this to be supported I would need someone with interest in this feature to develop it.

**Comment by valentijnscholten** [comment]
In my specific scenario it could be "as simple as" a flag to "ignore patch versions" when looking for "the latest version". But not sure if that is generic enough for an upstream flag.

**Comment by jetersen** [comment]
use exclude labels?

**Comment by valentijnscholten** [comment]
not sure I understand. but the goal is not to exclude PRs, but to let the release drafter find 1.0 as the latest release instead of 1.0.1. I haven't tried multiple workflows / config names, but looking the behaviour I think both workflows currently will find 1.0.1 as latest releases because all our releases are from master as per git flow.

**Comment by jetersen** [comment]
Currently release drafter only supports `semver` if you want to have release drafter list nothing for 1.1, than just delete the drafted release?

**Comment by valentijnscholten** [comment]
Maybe my explanation is not clear, but this is just git flow that we're using. Everything is released from master. And you can have hotfix releases next to normal releases.  My experience is that it is pretty common to have a hotfix/bufix on the latest published release, while there is already work being done and been merged in the next release in dev?

The problem is that the release draft now creates a draft 1.1 release with empty release notes, while ideally it should list PR100 and PR101 because those are not released yet.

Looking at the recent `filter-by-commitish` config option I think others might be releasing from different branches. So release regular releases from `release` and release hotfixes from `hotfix`? But that would be complicating things as you need to keep those branches up to date etc. I'd rather just follow git flow.

**Comment by jetersen** [comment]
a hotfix is just another patch released in semver.

**Comment by valentijnscholten** [comment]
> a hotfix is just another patch release in semver.

correct. so I think release draft should support those. currently all prs merged between the latest major or minor release and the patch release are lost.

**Comment by jetersen** [comment]
filter-by-commitish would just be previous `1.0.5` or `1.1.0`. I think you can write the necessary GitHub Action logic to properly handle the use case.

**Comment by valentijnscholten** [comment]
Would be able to elaborate? When looking at the code of release drafter I think it will find the latest release always, so 1.0.1. Even if you use `filter-by-committish`, it filter on `target_commitish` which is always `master` because all releases are done from `master`. So I don't see a way to achieve my goal, but I might be missing something.

**Comment by jetersen** [comment]
With v5.13.0 of release drafter you can run release drafter from any branch or any github action event.

**Comment by valentijnscholten** [comment]
I know, but the results is the same regardless which branch the action is started from. All releases are done from `master` so 1.0.1 is the latest release in time, so that will always be the one selected by release draft as `last release`.

**Comment by valentijnscholten** [comment]
I tried to take a look at the code and maybe add support for these "out of band" patch releases. It's straightforward to do something in `releases.js` to adjust the filtering. For example when the new release is a minor or major release, it should list all PRs since the previous minor/major release. 

However there are some scenario's I wasn't aware of and would require more changes to the code:
- release drafter will not rely on the version of an existing draft. it will overwrite it if it is different from the de "next version" resolved by the release drafter
- the input version is not taken into account when filtering releases in releases.js

Somehow I don't understand how other users are doing releases and not running into this problem. Out of band patch/bugfix releases should be pretty common? And releasing from master to as that's dictated by git flow.

I made an example repository where the problem shows: https://github.com/valentijnscholten/release-flow-demo/releases

Because I have release 1.0.1 patch release, the "add feature 2" PR from between 1.0.0 and 1.0.1 is not listed by the release drafter.

Tried to make a nice git graph, but when you start using PRs for releases and bringing branches in sync with each other it clutters the view a bit:
![image](https://user-images.githubusercontent.com/4426050/105574238-74f08f80-5d63-11eb-8445-37346769a34a.png)

**Comment by valentijnscholten** [comment]
I think a simple solution would be to allow an optional extra input `previous-version` which overrides the `lastRelease` calculated by release drafter. I have implemented this in my fork and am testing it: https://github.com/release-drafter/release-drafter/compare/master...valentijnscholten:prev-version-input?expand=1

**Comment by mkurz** [comment]
@valentijnscholten I think I might be able to help you. The core problem you face is that when using `filter-by-commitish`, currently all your releases will have a `target_commitish` set to `master`. However you can change that for _existing_ releases, without any impact on the release itself. Like see the GitHub API for updating a release: https://docs.github.com/en/rest/reference/repos#update-a-release:
> `target_commitish` ... Specifies the commitish value that determines where the Git tag is created from. Can be any branch or commit SHA. **Unused if the Git tag already exists. Default: the repository's default branch (usually master).**

I recommend you to carefully read the howto I came up with after I faced similiar problems: https://github.com/release-drafter/release-drafter/issues/656#issuecomment-806184887 In the end of that comment I better describe what `target_commitish` means and how you can change it. Maybe that howto can help you to come up with a solution to your problem.

**Comment by mkurz** [comment]
@sundowndev It's basically just an additional "field" / "property" / "attribute" that GitHub stores for a release. Please have a look at https://github.com/release-drafter/release-drafter/issues/656#issuecomment-806184887 - there I posted an image 

![image](https://user-images.githubusercontent.com/644927/112369276-4bf56800-8cdc-11eb-9951-e9c26dd9507b.png)

In this picture that `target_commitish` is `master` - so actually its the branch you create a release from. The GitHub api let's you update that `target_commitsh` for an existing release and calls it "commitish value" in its docs. (If you update that value for an _existing_ release, that does not change the branch, it just updates that `target_commitish` "field" of that release. It's just pure information)

**Comment by jetersen** [comment]
In can get there with target_commitsh.

Though I would suggest git flow is not the best approach to releases and CI/CD:

> Gitflow is a legacy Git workflow that was originally a disruptive and novel strategy for managing Git branches.
> Gitflow has fallen in popularity in favor of [trunk-based workflows](https://www.atlassian.com/continuous-delivery/continuous-integration/trunk-based-development), which are now considered best practices for modern continuous software development and [DevOps](https://www.atlassian.com/devops/what-is-devops) practices.
> Gitflow also can be challenging to use with [CI/CD](https://www.atlassian.com/continuous-delivery). This post details Gitflow for historical purposes.
> https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow
