### ISSUE TITLE
Release Drafter failed after replacing master branch with main branch

### ISSUE THREAD

**Issue by cliu123** [release-drafter/release-drafter#780]
After replacing master branch with main branch, I've [modified the release drafter configuration](https://github.com/opendistro-for-elasticsearch/security/pull/1023/files) file to use the new branch "main". But it's been [failing](https://github.com/opendistro-for-elasticsearch/security/runs/1858427070?check_suite_focus=true) since then. Any help will be appreciated.

Error: 💥 Release drafter failed with error: 
    HttpError: Validation Failed: {"resource":"Release","code":"invalid","field":"target_commitish"}
        at /home/runner/work/_actions/release-drafter/release-drafter/v5/dist/index.js:15171:23

**Comment by cliu123** [comment]
Resolved.

**Comment by jonbrohauge** [comment]
@cliu123 
Any pointers as to how you resolved it? I've hit the same snag.

**Comment by jetersen** [comment]
@jonbrohauge delete the existing draft

**Comment by jonbrohauge** [comment]
@jetersen  Thanks a bunch for stating the obvious ;-)
