### ISSUE TITLE
Forked PRs don't work with release-drafter action (and create an error)

### ISSUE THREAD

**Issue by rfay** [release-drafter/release-drafter#785]
On open-source projects, forked PRs are the standard way of interacting.

However, on a forked PR, with the release-drafter GitHub action, it's impossible to draft the release, so not only do people get an error, but their build fails.

`ERROR	 (HttpError): Resource not accessible by integration`

How is this to be used in an open-source forked-PR world? I assume this must be the thousandth time somebody has asked this, but I couldn't find it in the issues.

**Comment by jetersen** [comment]
Could you share your github action workflow?

**Comment by jetersen** [comment]
I guess I found it: https://github.com/rfay/actionjunk/blob/main/.github/workflows/release-drafter.yaml

The auto labeler has yet to be released in v5.
Auto labeler won't work with forks as the token cannot work across repo permissions, and that would be a problem with GitHub permissions.

**Comment by rfay** [comment]
Here's a test repository, https://github.com/rfay/actionjunk, the workflow is https://github.com/rfay/actionjunk/blob/main/.github/workflows/release-drafter.yaml

You'll note that PRs from me, the owner, get processed successfully, see https://github.com/rfay/actionjunk/releases/tag/untagged-a8baa3aaf54b5ca2c10d

However, PRs from non-member users get a failure, see https://github.com/rfay/actionjunk/pull/14

**Comment by jetersen** [comment]
If your after the drafting portion of release drafter, that does not make sense to run on a pull request that has yet to be merged.

**Comment by rfay** [comment]
I don't want it to run on a PR that has not been merged. I just copied the example!

**Comment by jetersen** [comment]
The example is just that an example, please adapt it to your use case :)

**Comment by rfay** [comment]
Sorry, I know I'm naive. But I expect a basic example to not require extensive understanding of the application. I really appreciate your quick support. But could you please provide an example that "just works" as the first example in the docs?

IMO the idea behind using Github actions is not to have to know the details of how to "adapt", but mostly to plug-and-play.  Lots of people who come here are not going to know what to do to make it work the way they want, and they're hoping it will just be easy... or at least that the docs will guide them to a resolution.

**Comment by jetersen** [comment]
The basic example does work. Perhaps not according to what you want.

I suggest you simply remove the pull request bit inside the `on` part of the GitHub action.

**Comment by rfay** [comment]
So my problem is not the workflow, but the release drafter template? I was focused on the workflow. 

I did in fact remove the pull request part, https://github.com/rfay/actionjunk/blob/main/.github/workflows/release-drafter.yaml and I used the jenkins example for the template. 

Then I pulled a forked PR, https://github.com/rfay/actionjunk/pull/14

Nothing happens, draft release doesn't get updated. https://github.com/rfay/actionjunk/releases/tag/untagged-a8baa3aaf54b5ca2c10d

**Comment by jetersen** [comment]
Your default branch is not master, but main ;)

**Comment by rfay** [comment]
Easy to update that example to cover master and main. Thanks for your good eye. After all these years of using "master", and now they want "main". I know I can change the default. 

It says the `branches:` default is "all" though, so I just removed the `branches:` section since it says that's optional. That didn't work. 

But then I changed it to list both master and main branches, and it works, thanks!

Want a PR to the README example that lists both master and main?

**Comment by jetersen** [comment]
> Want a PR to the README example that lists both master and main?

I do not see how that would solve the real issue, as someone could have `dev`, `prod` or whatever as default branch.

**Comment by rfay** [comment]
Mostly people who are trying things out will have master or main as default branches on github. We all know it's possible to use something out.

**Comment by rfay** [comment]
How do you use the default "all" for branches then, since the branch list is supposed to be optional? That would be a good example then. Provide the commented-out branch list, but use the default "all branches"

**Comment by rfay** [comment]
I do encourage you to refactor the examples to examples that

1. Work the first time, simplest case, if possible. For people like me.
2. Work with forked PRs
3. Default to pulls, not opening PRs

**Comment by jetersen** [comment]
I prefer to leave it. This also serves those who have privat repos and there the autolabeler is also useful.
Again any action that works with pull requests will have issues with pull requests, I don't see that changing anytime soon.
So should all actions that works on pull request change? Maybe not, perhaps we should ask GitHub to enable those actions to actually work with forks.

Take my action: https://github.com/jetersen/ghaction.file.sync which is not a plug and play action and requires you to read the docs.
I don't think it is too much to ask for someone to read the docs and perhaps explore who uses the action and see how they use it.

**Comment by rfay** [comment]
Well, if you weren't so generous with support, and if I hadn't opened an issue... I would have just walked away and never come back. So simpler is better for most people.

Perhaps you wish Github hadn't sent out an email to every single member suggesting this action :)

Part of my frustration is that the *other* one I tried from that email is completely unmaintained, doesn't even use a working yaml, and if you fix the yaml, it doesn't work. So this was #2 :(

Github has really, really messed up with Actions IMO because they forgot how many people need things to work with the public fork-PR workflow. And then that dirty secret doesn't get mentioned anywhere,.

**Comment by gilbertsoft** [comment]
> 
> Github has really, really messed up with Actions IMO because they forgot how many people need things to work with the public fork-PR workflow. And then that dirty secret doesn't get mentioned anywhere,.

Hey @rfay 

To enable write permissions for forks use the event `pull_request_target` instead of `pull_request` see https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#pull_request_target.

**Comment by rfay** [comment]
Thanks for that. But yeah, it doesn't help with trying to use secrets in any forked-pr workflow, even if they're throwaway secrets.
