### ISSUE TITLE
Feature request: output PR from merge to master

### ISSUE THREAD

**Issue by Nuru** [release-drafter/release-drafter#794]
This module is able to find the PR that was the source of the merge to master on the `push` to `master` event. I have not found an easy way to do that or another action that does it. Please, publish an action that does just that. Please also include it in the outputs of this action.

My motivation: I want to be able to control the `draft` and `pre-release` options based on labels on the PR.

**Comment by jetersen** [comment]
We welcome contributions.

**Comment by Nuru** [comment]
> We welcome contributions.
> Although with multiple PRs how would you determine the "source"

Right now `release-drafter` collects all the labels to determine how to organize the release notes and determine the next version number. I should be trivially easy to 
1. output the PRs in the release
2. output the PR merge that triggered the action if this action is running on a push to the default branch
3. determine draft/publish and pre-release status based on labels

I would offer the enhancements if I had a clue how to do them, but I know nothing about the libraries and APIs this module uses, the build environment, or how to test any of this.

Meanwhile I found [action-get-merged-pull-request](https://github.com/actions-ecosystem/action-get-merged-pull-request) which is close enough, so I am closing this issue.

**Comment by jetersen** [comment]
https://github.com/actions-ecosystem/action-get-merged-pull-request does seem to already solve what you were after 🙂
