### ISSUE TITLE
Branch rename breaks drafter

### ISSUE THREAD

**Issue by wjk** [release-drafter/release-drafter#817]
I have renamed my `master` branch to `main`, as is popular these days. I have then merged more PRs into the `main` branch, and now release-drafter chokes [with this error](https://github.com/wjk/MSIExtractApp/runs/2136502691) (which is not reported as one; the workflow still succeeds), which I presume is because it's still trying to find the `master` branch. What can I do to fix this?

**Comment by jetersen** [comment]
Delete the latest draft.

**Comment by wjk** [comment]
Worked like a charm. Thanks so much!
