### ISSUE TITLE
Error: Resource not accessible by integration

### ISSUE THREAD

**Issue by mvorisek** [release-drafter/release-drafter#820]
There is some issue with Release Drafter, see https://github.com/atk4/data/runs/2165917643#step:2:16

Can someone confirm this is a Release Drafter issue or does this https://github.com/atk4/data/blob/develop/.github/workflows/release-drafter.yml config require some change?

Notes/observations:

- CI passed with green icon, but in log there is an `Error: Resource not accessible by integration` error and https://github.com/atk4/data/releases is unchanged.
- Github switched to `Ubuntu 20.04` from `Ubuntu 18.04.5`, is this issue related?

**Comment by chris-araman** [comment]
I just hit this. I was able to resolve it by ensuring the `GITHUB_TOKEN` for actions running for the repository have write access.
https://docs.github.com/en/actions/reference/authentication-in-a-workflow#modifying-the-permissions-for-the-github_token

**Comment by jetersen** [comment]
You can either provide a custom GitHub token with enough permissions either personal token or an app token. There are actions that can generate an app token.
By default the `GITHUB_TOKEN` should have enough permissions to create a release.

On pull requests it might be an idea to use `on: pull_request_target` for triggering autolabeler.
