### ISSUE TITLE
Generate draft between two tags

### ISSUE THREAD

**Issue by lucacome** [release-drafter/release-drafter#821]
A new tag was created and all the changes in the draft are now lost. 
Is there a way to get a list of all the changes between the two tags?
Or trigger the draft again?

**Comment by nikophil** [comment]
Hello,
I'm having the same problem: it seems that release drafter rely on tags dates.

If some feature PRs are merged on a `develop` branch, then a hotfix is merged on master branch, a new release draft will not contain PRs merged before hotfix.

Is there a workaround please?

thanks :)

**Comment by lucacome** [comment]
I'm closing this issue since there wasn't any activity in over 4 months
