### ISSUE TITLE
Tag always ends up on the main-branch

### ISSUE THREAD

**Issue by danielcweber** [release-drafter/release-drafter#824]
Hi,

first of all, thanks for this great workflow.

I develop on the "main" branch. On a release, I create a branch "rel" and bump the version (in a version.json), thereby creating a new commit). "rel" is now one commit ahead of "main".

I override the "tag" and the "commitish" parameter of the workflow. Commitish seems to successfully pickup "rel" as the branch to work on. Yet, the tag always ends up on "main".

My workflow is [here](https://github.com/ExRam/ExRam.Gremlinq/blob/main/.github/workflows/build.yml#L191). The latest run is [this](https://github.com/ExRam/ExRam.Gremlinq/runs/2204557867?check_suite_focus=true). Note that I have forcefully pushed the 8.4.0-tag to be on the right commit.

Thanks a lot.

**Comment by danielcweber** [comment]
Apparently, the "commitish" parameter doesn't make it to the "target_commitish" parameter of the createRelease method in OctoKit: 

![image](https://user-images.githubusercontent.com/1899410/113871547-4e16f680-97b3-11eb-8690-03b38fb48fad.png)

I had a thorough look into the sources but can't tell where it gets lost.

**Comment by gauravsaini** [comment]
Facing the same issue.
