### ISSUE TITLE
Release drafter WF does not tag and title release draft

### ISSUE THREAD

**Issue by Imipenem** [release-drafter/release-drafter#825]
Hey,

I currently have an issue with release drafter:
The example repo is at: https://github.com/Imipenem/exploding-springfield/
My `release-drafter.yml` file: https://github.com/Imipenem/exploding-springfield/blob/main/.github/release-drafter.yml
And my workflow file: https://github.com/Imipenem/exploding-springfield/blob/main/.github/workflows/release-drafter.yml

As can be seen, I specified a `tag-template` and `name-template` which I expect to be the tag/release title of the drafted release.
But this does not work, so my draft is not tagged and not titled (which I had to do manually).

How can I solve this issue? I want to specify my own custom version, if possible.

Best

**Comment by jetersen** [comment]
That is only the case for the first release.

**Comment by Imipenem** [comment]
@jetersen  I see, thanks yes it worked for the second release.

However, I encountered a new issue: Sometimes (I really dont know why) my PRs got labeled correctly (like bug or feature/enhancement) but then in the draft, they are not grouped into the right category like here: https://github.com/Imipenem/exploding-springfield/releases/tag/0.1.1

I'm really confused what's happening here?

**Comment by jetersen** [comment]
Based on your workload for release drafter: https://github.com/Imipenem/exploding-springfield/blob/52f3c4ee5233921c35ccf0399d9b9777dce7d426/.github/workflows/release-drafter.yml
The draft was created from the PR.
So either you need to rerun the action after the PR is merged or change it so that release drafter draft on push to a branch.

**Comment by Imipenem** [comment]
@jetersen  Hm, this did not work like here: https://github.com/Imipenem/exploding-springfield/releases/tag/0.1.2
This should be in the `Feature` category. May be because the PR that pushed to the branch was not labeled? Do i need to run the WF on both, PR and push?

**Comment by jetersen** [comment]
You need on PR for auto labeler and push for updating the draft.

Release drafter draft based on merged PR hence you need a push event to update the draft correctly.

**Comment by Imipenem** [comment]
Thanks, I will try it
