### ISSUE TITLE
"ValidationError: child "template" fails because ["template" is required]\n'

### ISSUE THREAD

**Issue by JustinGrote** [release-drafter/release-drafter#835]
https://github.com/JustinGrote/Press/actions/runs/727435035

I've tried every combination of just the workflow with no config, specifying the config with only template, etc. but I always get this message.

**Comment by jetersen** [comment]
The config has to be on the default branch.

**Comment by JustinGrote** [comment]
@jetersen thank you! makes testing a little tricky but it's not a big deal. I submitted a PR to clarify that in the readme. Thanks.

**Comment by SebSept** [comment]
Damned ! I wish I had this information 2 hours ago :/

**Comment by kreempuff** [comment]
@jetersen is there a reason it **must** be on the default branch? This has bitten me quite a few times, it'd be nice if it was configurable. Happy to contribute a change if it's not a GitHub limitation

**Comment by jetersen** [comment]
> @jetersen is there a reason it **must** be on the default branch? This has bitten me quite a few times, it'd be nice if it was configurable. Happy to contribute a change if it's not a GitHub limitation

Not a github limit. Could be patched.

**Comment by JustinGrote** [comment]
Ran into this again, drives me crazy I can't test my release drafters and have to iterate on main to get it working

**Comment by kreempuff** [comment]
@JustinGrote I'll tackle this when I get some time in the near future 😬

**Comment by jetersen** [comment]
> > @jetersen is there a reason it **must** be on the default branch? This has bitten me quite a few times, it'd be nice if it was configurable. Happy to contribute a change if it's not a GitHub limitation
> 
> Not a github limit. Could be patched.

Patching it would result in security issues.

**Comment by JustinGrote** [comment]
@jetersen why would it be a security issue? PRs won't have a sufficient GITHUB_TOKEN to draft a release, and I can control who creates branches in my repo and what branch those actions enact. Only people who could "abuse" this would be people who can draft their own releases anyways, maybe you can clarify?

**Comment by jetersen** [comment]
Person with repo write permission can modify the action to run draft and create a release and most likely release a binary with nasty bits in it.

GITHUB token has permission to both draft and publish releases as the action even offers to publish a release.

I prefer that the action requires to modified on the default branch as that usually provides extra safe guards with branch protection.
