### ISSUE TITLE
Some questions regarding the GitHub Action

### ISSUE THREAD

**Issue by Andre601** [release-drafter/release-drafter#860]
This looks like a really promising GitHub Action I would like to use in one of my projects.

But before I can do that would I like to get some questions answered, so that I won't accidentally encounter issues on the way.

**1st Question:**
Does this action only recognize/handle Pull requests? I saw on the readme that the workflow uses `push` and that `pull_request` only is needed for the auto-labeler.
Would it also recognize and handle direct pushes to specific branches?
I currently don't have a specific PR setup and usually directly push changes to a `development` branch before merging that into the `master` branch that would trigger a build and release on my CI Server.

**2nd Question:**
Could I use this action in combination with another action to create a release and then build and upload files to it?
Right now do I see the issue, that Actions don't trigger other Actions outside of the workflow_dispatch one, so there would be an issue to find/recognize a release from a Workflow_dispatch alone...

**Comment by jetersen** [comment]
1: Should support any branch.
2: Should be supported now to trigger on workflow_dispatch. You should be able to use other actions to get build artifacts uploaded to the published release.
