### ISSUE TITLE
Running release-drafter on self-hosted runner, using GitHub Enterprise and a Corporate certificate chain

### ISSUE THREAD

**Issue by jonbrohauge** [release-drafter/release-drafter#875]
I am testing release-drafter on our test GitHub Enterprise instance.
I have a self-hosted GitHub runner working.
When I try to execute release-drafter, I get, what I think is, a certificate issue.
```
stack: 'HttpError: request to https://ghetest.domain.local/api/v3/repos/action-test/action-repo/contents/.github%2Frelease-drafter.yml failed, reason: unable to verify the first certificate\n' +
    '    at /home/bootstrap/actions-runner/_work/_actions/release-drafter/release-drafter/v5.15.0/dist/index.js:15352:11\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:93:5)',
  type: 'Error'
```

Since I'm not sure how the GitHub Action executes on the runner, how can I configure either the runner or release-drafter to accept the corporate certificate chain?

There was no issue in downloading release-drafter onto the runner, and the server/runner itself works with the corporate certificates.

**Comment by jonbrohauge** [comment]
@jetersen In which context should I set the Env Var? As the current user on the runner, where the runner-application is placed, or does it have to be in root-context?

**Comment by jetersen** [comment]
since your in control of the runner, I suggest adding the NODE_EXTRA_CA_CERTS on the runner so any node process ie. other GitHub action is also able to function with the cert.

**Comment by jonbrohauge** [comment]
@jetersen Thanks for the reminding me of the obvious:

Adding `NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt` to the `.env`-file

I will be looking into virtual environments next.

**Comment by jetersen** [comment]
@jonbrohauge Your welcome!
