### ISSUE TITLE
Acquire verified badge on release-drafter action

### ISSUE THREAD

**Issue by ssbarnea** [release-drafter/release-drafter#896]
Please read https://github.community/t/how-to-become-verified-creator-of-a-github-action/116009/3 and start the process for getting verified  as that green badge is quite important for establishing trust. I know several organizations that have policies that do only allow verified actions to run on them.

**Comment by dennisroche** [comment]
Our organization requires only verified actions. Either we have to jusify why we need to use release-drafter or find a verified alternative :/.

**Comment by jetersen** [comment]
Think @toolmantim and @TimonVS are the once with the power to start verification.
To my knowledge I have limited access being only able to release new version.

Although I will say having verification as an requirement seems silly. Especially when release-drafter came out before the verification program 🗡️

**Comment by ssbarnea** [comment]
With the growing number of actions being published having a way to distinguish between random one or more official becomes quite useful. At least github verification process is not like twitter one ;)

**Comment by jetersen** [comment]
random? oh come on `release-drafter/release-drafter` it cannot get any more official 😅 

I would if I could. But as I mentioned I am not able to.

**Comment by jetersen** [comment]
![image](https://user-images.githubusercontent.com/1661688/145834106-2fe88cb3-253d-41ba-9464-80b9d6d9aa92.png)

First part done :)

**Comment by jetersen** [comment]
Second part is done, though now the waiting game begins.
![image](https://user-images.githubusercontent.com/1661688/145854779-cf0595c7-e081-49f9-b4b9-eb349d310c67.png)

**Comment by jetersen** [comment]
@ssbarnea any idea on how long the verification process takes? 🤔

**Comment by ssbarnea** [comment]
No idea, I guess that being second part of December does not help. Anyway, you all did your part so now we only need patience.

**Comment by jetersen** [comment]
I am not seeing a verified badge anyone on the market place 😅 Not sure where it should show.

![image](https://user-images.githubusercontent.com/1661688/146578298-1b82cce2-08cf-4c74-a719-db62c7fbb1ad.png)

**Comment by jetersen** [comment]
Not possible for anybody to get a verified badge apart from "GitHub partner organizations"

> Hi Joseph,
>
> Please note that the publisher verification process is currently applicable only to Apps and not Actions.
>
> Only GitHub partner organizations can receive a Verified Creator badge for Actions. Currently, there is no way to request verification. Creators are verified because they have an existing relationship with GitHub, and GitHub has worked closely with the creator to create their actions. We are continuing to evaluate this process, and we may open it up more broadly in the future.
>
> I hope this clarifies things and if we can be of further assistance, please let us know.
>
> Kind Regards,
>
> GitHub Marketplace Team

**Comment by noinarisak** [comment]
Wondering if this Issue could be reopen?  Our GHE also requires verified creator status, and I would love to reuse the existing workflow YAML that I created with Release Drafter. Hopefully, it is not dead in the water, and GitHub Marketing figured out its policy on open-source Github Actions being verified

**Comment by Th0masL** [comment]
Same thing here, my company only allows verified creators on GitHub Actions
