### ISSUE TITLE
Adding newlines in change-template

### ISSUE THREAD

**Issue by JoeCMorgan** [release-drafter/release-drafter#902]
Apologies if I'm missing the obvious here, but I can't seem to add new lines in the `change-template`. I've tried pretty much everything from yaml to mdx, e.g. :
```
change-template: "$TITLE @$AUTHOR (#$NUMBER)
\
\
$BODY"
```

I just need to add a new line between the PR Title and the body.

**Comment by jetersen** [comment]
@JoeCMorgan https://yaml-multiline.info/

**Comment by JoeCMorgan** [comment]
Thanks for the reply @jetersen - by my logic then the following should work:
```
change-template: "$TITLE @$AUTHOR (#$NUMBER)

    $BODY"
template: |
    $CHANGES
```

Based off the double quotes section 
> Newlines can also be added by leaving a blank line.\n
····Leading whitespace on lines is ignored.

And the fact that I'm using the literal block style indicator for the `template`. However I'm still not getting any line breaks between  `(#$NUMBER)` and `$BODY`?

**Comment by jetersen** [comment]
change-template: |
	$TITLE @$AUTHOR (#$NUMBER)

    $BODY

**Comment by JoeCMorgan** [comment]
That's done it, thanks a lot @jetersen!
