### ISSUE TITLE
Output compared from tag/branch

### ISSUE THREAD

**Issue by guilhermeblanco** [release-drafter/release-drafter#924]
Currently the output only provides the tag that is bound to the release (unless it's a draft, that remains as untagged-XXX).
As part of changelog generation, it would be great if we could expose both at changelog template and also as an output which was the compared tag or branch.

By supporting at template level, we could write "Changes since vX.Y.Z", where "vX.Y.Z" is the from tag that the created release was compared for changelog generation.

By supporting at an output level, it could determine if a given path was changed in a release to trigger a specialized set of instructions.

**Comment by jetersen** [comment]
You should be able to add inside your template:

```yaml
template: |
  Changes since $PREVIOUS_TAG

  $CHANGES
```

**Comment by jetersen** [comment]
See use-case:

https://github.com/release-drafter/release-drafter/blob/3bc19058001dbbdd774f09eb627a189c88e7336e/.github/release-drafter.yml#L8

**Comment by jetersen** [comment]
Unless what your asking for is more action output variables?
