### ISSUE TITLE
commitish configuration option not present in schema.json file

### ISSUE THREAD

**Issue by menno-ll** [release-drafter/release-drafter#971]
The [Configuration options in the readme](https://github.com/release-drafter/release-drafter#configuration-options) state that we can use the `commitish` property to define which branch a release is created for.
However, looking at the [`schema.json`](https://github.com/release-drafter/release-drafter/blob/master/schema.json) file, it's not present there.

**Comment by jetersen** [comment]
Feel free to open a PR.

**Comment by menno-ll** [comment]
Thereyougo! :)
https://github.com/release-drafter/release-drafter/pull/989
