### ISSUE TITLE
Possible to use autolabeler without creating a draft release on unmerged PR?

### ISSUE THREAD

**Issue by ahatzz11** [release-drafter/release-drafter#977]
Currently when a PR is opened it autolabels, but it also adds that unmerged PR to the release draft. I would like to autolabel my PRs, but I only want merged PRs to be added to my draft. Is this possible?

**Comment by harrylewis** [comment]
Hey @ahatzz11 👋 

I was also just experiencing this issue as well today, and came across #917. It explains about an undocumented workflow configuration, `disable-releaser`, which can be used.

This PR, https://github.com/sbgisen/.github/pull/26, contains a good example of how this could be used for your scenario.

**Comment by ahatzz11** [comment]
@harrylewis thanks for the info! This completely stopped release-drafter from running, which means that the autolabeler also didn't run. 

Am I able to have the auto-labeler part run without generating a release? Also I think using `disable-releaser` is kind of a roundabout way of fixing that when you could just turn off the `pull_request` events if it just 100% disables it.
